
DROP TABLE "INNOCITY"."CREDIT_CARD";
CREATE TABLE "INNOCITY"."CREDIT_CARD" (
  "CARD_NUMBER" NUMBER,
  "CARD_USERNAME" VARCHAR2(50 BYTE),
  "CARD_TYPE" VARCHAR2(50 BYTE),
  "CVC" NUMBER,
	"EXPIRATION" DATE,
	"CUSTOMERID" NUMBER
)
TABLESPACE "INNOCITY_TABSPACE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table CREDIT_CARD
-- ----------------------------
ALTER TABLE "INNOCITY"."CREDIT_CARD" ADD CONSTRAINT "CREDIT_CARD_PK" PRIMARY KEY ("CARD_NUMBER");

-- ----------------------------
-- Foreign Keys structure for table CREDIT_CARD
-- ----------------------------
ALTER TABLE "INNOCITY"."CREDIT_CARD" ADD CONSTRAINT "CREDIT_CARD_FK" FOREIGN KEY ("CUSTOMERID") REFERENCES "INNOCITY"."CUSTOMER" ("CUSTOMERID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
