
DROP TABLE "INNOCITY"."MOBILE_BANKING";
CREATE TABLE "INNOCITY"."MOBILE_BANKING" (
  "PHONE_NUMBER" NUMBER,
  "SERVICE_PROVIDER" VARCHAR2(50 BYTE),
	"CUSTOMERID" NUMBER
)
TABLESPACE "INNOCITY_TABSPACE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table MOBILE_BANKING
-- ----------------------------
ALTER TABLE "INNOCITY"."MOBILE_BANKING" ADD CONSTRAINT "MOBILE_BANKING_PK" PRIMARY KEY ("PHONE_NUMBER");

-- ----------------------------
-- Foreign Keys structure for table MOBILE_BANKING
-- ----------------------------
ALTER TABLE "INNOCITY"."MOBILE_BANKING" ADD CONSTRAINT "MOBILE_BANKING_FK" FOREIGN KEY ("CUSTOMERID") REFERENCES "INNOCITY"."CUSTOMER" ("CUSTOMERID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
