CREATE OR REPLACE PROCEDURE "ADD_NEW_ROOM_TYPE"(RTID IN NUMBER, RT IN VARCHAR2, HID IN NUMBER, BT IN VARCHAR2, COST IN NUMBER, DISC IN NUMBER,EXISTING OUT NUMBER) AS
	
BEGIN
	SELECT ROOMTYPEID INTO EXISTING FROM ROOM_TYPE WHERE HOTELID = HID AND UPPER(ROOMTYPE_NAME) = UPPER(RT);
	
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		EXISTING := 0;
		INSERT INTO ROOM_TYPE(ROOMTYPEID, ROOMTYPE_NAME, BED_TYPE, COST_PER_DAY, DISCOUNT, HOTELID) VALUES(RTID,
		INITCAP(RT), INITCAP(BT), COST, DISC, HID);
END;