CREATE OR REPLACE PROCEDURE "ADD_NEW_ROOM"(HID IN NUMBER, RT_NAME IN VARCHAR2, FL_NUM IN NUMBER, RID IN NUMBER) AS 
	RTID NUMBER;
BEGIN
	SELECT ROOMTYPEID INTO RTID FROM ROOM_TYPE WHERE HOTELID = HID AND ROOMTYPE_NAME = RT_NAME;
	INSERT INTO ROOM(ROOMID, FLOOR_NUMBER, HOTELID, ROOMTYPEID) VALUES(RID, FL_NUM, HID, RTID);
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO DATA');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('OTHER ERROR');
END;