CREATE OR REPLACE PROCEDURE "ADD_NEW_PAID_SERVICE"(S_TYPE IN VARCHAR2, S_SUBTYPE IN VARCHAR2,
COST IN NUMBER, HID IN NUMBER, EXISTING OUT NUMBER) 
AS
	SID NUMBER;
BEGIN
	SELECT SERVICEID INTO EXISTING FROM SERVICE WHERE HOTELID = HID AND SERVICE_TYPE = INITCAP(S_TYPE) AND 
	SERVICE_SUBTYPE = INITCAP(S_SUBTYPE);
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		EXISTING := 0;
		SID := GENERATE_ID('SERVICE', 'SERVICEID');
		INSERT INTO SERVICE VALUES(SID, INITCAP(S_TYPE), INITCAP(S_SUBTYPE), COST, HID);
END;