CREATE OR REPLACE FUNCTION "LOGIN_HOTEL"(HID IN VARCHAR2, PASS IN VARCHAR2) RETURN NUMBER
AS
	RES NUMBER;
BEGIN
	SELECT HOTELID INTO RES FROM HOTEL WHERE HOTELID = HID AND PASSWORD = PASS;
	RETURN RES;
EXCEPTION 
	WHEN NO_DATA_FOUND THEN 
		RETURN 0;
	WHEN OTHERS THEN
		RETURN 0;
END;