CREATE OR REPLACE FUNCTION "LOGIN_CUSTOMER"(UNAME IN VARCHAR2, PASS IN VARCHAR2) RETURN INT -- VARCHAR2
AS
	CID NUMBER;
BEGIN
	SELECT CUSTOMERID INTO CID FROM CUSTOMER WHERE USERNAME = UNAME AND PASSWORD = PASS AND ISVERIFIED = 'YES';
	RETURN CID;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		RETURN 0;
END;