CREATE OR REPLACE FUNCTION "REGISTER"(C_NAME IN VARCHAR2, C_EMAIL IN VARCHAR2, C_UNAME IN VARCHAR2, C_PASSWORD IN VARCHAR2,C_GENDER IN VARCHAR2, C_STREET IN VARCHAR2, C_ZIPCODE IN VARCHAR2, C_CITY IN VARCHAR2, C_COUNTRY IN VARCHAR2,
C_PHONE IN VARCHAR2)
RETURN NUMBER
AS
	CID NUMBER;
	EXISTING NUMBER;
BEGIN
	SELECT COUNT(*) INTO EXISTING FROM CUSTOMER WHERE USERNAME = C_UNAME;
	IF EXISTING > 0 THEN 
		CID := 0;
	ELSE 
		CID := GENERATE_ID('CUSTOMER', 'CUSTOMERID');
		INSERT INTO CUSTOMER VALUES(CID, C_NAME, C_EMAIL, C_UNAME, C_PASSWORD, C_GENDER, C_STREET, C_ZIPCODE,
		C_CITY, C_COUNTRY, C_PHONE, 'NO');
	END IF;
	RETURN CID;
END;