create table Hotel_facility (
                                hotelID INT,
                                facilities VARCHAR(30)
);
insert into Hotel_facility (hotelID, facilities) values (216, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (213, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (252, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (384, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (99, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (438, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (136, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (442, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (173, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (180, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (38, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (47, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (215, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (471, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (466, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (103, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (420, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (348, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (423, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (143, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (444, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (470, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (63, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (142, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (418, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (141, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (481, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (370, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (251, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (104, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (350, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (483, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (368, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (281, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (382, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (447, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (490, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (300, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (254, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (267, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (484, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (225, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (225, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (122, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (455, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (256, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (93, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (410, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (407, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (331, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (198, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (111, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (413, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (40, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (418, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (190, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (16, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (188, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (273, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (413, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (163, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (15, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (423, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (52, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (82, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (78, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (358, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (435, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (11, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (55, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (226, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (95, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (399, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (113, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (389, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (30, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (415, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (175, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (253, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (321, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (248, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (114, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (219, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (444, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (121, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (346, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (173, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (241, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (257, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (428, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (130, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (495, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (307, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (137, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (391, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (123, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (424, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (431, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (116, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (116, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (61, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (486, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (484, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (439, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (371, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (381, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (46, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (46, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (440, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (98, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (63, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (30, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (22, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (354, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (336, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (70, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (373, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (194, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (191, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (274, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (152, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (181, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (125, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (422, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (194, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (241, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (168, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (266, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (259, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (110, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (131, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (161, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (128, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (351, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (307, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (139, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (148, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (117, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (345, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (76, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (481, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (178, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (38, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (406, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (149, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (358, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (453, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (52, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (382, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (280, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (462, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (238, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (292, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (296, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (124, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (459, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (466, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (280, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (182, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (424, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (176, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (153, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (118, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (468, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (373, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (118, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (238, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (258, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (213, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (36, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (316, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (97, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (355, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (465, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (485, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (34, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (75, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (260, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (250, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (466, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (399, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (172, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (12, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (135, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (439, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (305, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (151, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (344, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (413, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (264, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (246, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (256, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (248, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (40, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (257, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (218, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (435, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (389, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (213, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (462, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (345, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (432, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (245, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (324, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (63, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (370, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (363, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (384, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (271, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (433, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (76, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (320, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (126, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (140, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (459, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (364, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (377, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (321, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (289, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (381, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (226, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (495, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (496, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (339, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (417, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (466, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (89, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (69, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (330, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (364, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (154, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (253, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (326, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (2, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (345, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (205, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (263, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (62, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (496, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (459, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (74, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (210, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (85, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (301, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (445, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (89, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (404, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (326, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (273, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (86, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (122, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (268, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (194, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (469, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (251, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (191, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (55, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (173, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (71, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (204, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (131, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (466, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (299, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (26, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (93, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (36, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (233, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (264, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (136, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (297, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (96, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (1, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (251, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (210, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (481, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (63, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (355, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (320, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (368, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (374, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (163, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (44, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (186, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (465, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (350, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (350, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (393, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (120, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (400, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (301, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (301, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (479, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (470, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (209, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (333, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (127, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (164, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (152, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (302, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (425, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (487, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (178, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (9, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (138, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (8, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (51, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (382, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (372, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (114, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (40, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (241, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (490, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (146, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (52, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (355, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (195, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (18, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (464, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (150, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (134, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (235, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (377, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (440, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (408, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (495, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (86, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (482, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (96, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (471, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (454, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (7, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (268, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (417, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (415, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (92, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (448, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (273, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (226, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (369, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (56, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (219, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (440, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (401, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (392, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (22, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (491, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (351, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (186, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (217, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (460, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (410, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (405, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (269, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (450, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (109, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (491, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (378, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (411, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (394, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (327, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (90, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (68, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (265, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (104, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (268, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (227, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (44, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (478, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (477, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (183, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (439, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (281, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (142, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (455, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (88, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (379, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (225, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (81, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (140, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (406, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (187, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (406, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (69, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (31, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (91, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (477, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (162, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (296, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (228, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (147, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (278, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (106, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (246, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (354, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (350, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (392, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (227, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (218, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (300, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (228, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (374, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (220, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (23, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (123, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (251, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (444, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (273, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (301, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (103, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (380, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (313, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (483, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (442, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (145, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (417, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (49, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (363, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (192, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (187, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (77, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (241, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (14, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (279, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (382, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (14, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (454, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (424, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (265, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (195, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (336, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (465, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (251, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (75, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (166, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (213, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (62, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (169, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (1, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (465, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (29, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (42, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (237, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (317, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (147, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (78, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (496, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (212, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (364, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (136, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (232, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (55, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (237, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (407, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (359, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (25, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (409, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (367, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (371, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (493, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (330, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (446, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (113, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (456, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (257, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (3, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (215, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (460, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (458, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (471, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (1, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (138, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (432, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (116, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (230, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (326, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (352, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (262, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (114, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (247, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (40, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (435, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (342, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (294, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (313, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (154, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (148, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (114, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (370, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (441, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (245, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (57, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (258, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (282, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (6, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (356, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (11, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (372, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (413, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (455, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (262, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (83, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (240, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (147, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (249, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (409, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (279, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (86, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (162, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (396, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (126, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (372, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (100, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (347, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (287, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (60, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (119, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (400, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (348, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (365, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (360, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (443, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (357, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (324, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (12, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (233, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (267, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (201, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (366, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (282, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (348, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (51, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (223, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (427, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (12, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (240, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (307, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (79, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (498, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (51, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (76, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (339, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (225, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (261, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (315, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (37, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (347, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (110, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (379, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (271, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (498, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (99, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (229, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (337, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (52, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (304, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (279, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (268, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (16, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (190, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (113, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (385, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (34, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (6, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (66, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (448, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (184, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (10, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (163, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (175, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (19, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (213, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (249, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (417, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (332, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (345, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (418, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (267, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (66, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (317, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (347, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (233, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (16, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (323, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (466, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (155, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (122, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (379, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (170, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (401, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (406, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (444, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (135, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (227, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (215, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (266, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (45, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (215, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (456, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (323, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (99, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (206, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (457, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (40, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (235, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (458, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (419, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (443, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (371, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (156, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (314, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (492, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (139, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (393, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (61, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (490, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (428, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (438, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (359, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (147, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (91, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (213, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (444, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (279, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (326, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (493, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (468, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (327, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (329, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (314, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (302, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (304, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (323, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (237, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (422, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (411, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (316, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (389, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (256, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (188, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (332, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (375, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (26, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (343, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (69, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (286, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (97, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (133, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (416, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (146, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (490, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (459, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (201, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (339, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (284, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (184, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (283, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (234, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (150, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (68, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (187, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (264, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (336, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (179, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (378, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (410, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (367, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (190, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (10, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (172, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (144, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (231, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (207, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (499, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (138, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (217, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (345, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (239, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (56, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (499, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (433, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (76, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (500, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (466, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (189, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (161, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (202, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (439, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (219, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (404, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (270, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (383, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (128, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (465, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (16, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (461, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (90, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (259, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (261, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (249, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (63, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (415, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (22, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (443, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (176, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (115, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (396, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (221, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (67, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (239, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (235, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (269, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (35, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (405, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (498, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (228, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (474, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (122, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (382, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (291, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (326, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (366, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (220, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (329, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (448, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (240, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (114, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (197, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (58, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (55, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (123, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (463, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (77, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (173, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (351, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (277, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (248, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (120, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (111, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (392, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (406, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (476, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (94, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (362, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (147, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (80, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (347, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (62, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (435, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (165, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (324, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (26, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (469, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (126, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (315, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (447, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (355, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (329, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (483, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (438, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (364, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (274, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (468, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (368, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (240, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (155, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (415, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (396, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (361, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (318, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (75, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (346, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (286, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (268, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (86, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (179, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (231, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (181, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (292, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (407, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (10, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (465, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (194, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (18, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (57, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (240, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (485, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (237, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (389, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (185, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (463, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (255, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (158, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (295, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (422, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (92, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (488, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (23, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (284, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (190, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (320, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (233, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (339, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (314, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (380, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (435, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (136, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (65, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (480, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (257, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (267, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (387, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (62, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (248, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (387, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (250, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (279, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (136, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (406, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (77, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (172, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (337, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (56, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (209, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (468, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (227, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (255, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (48, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (281, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (232, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (331, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (274, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (461, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (140, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (301, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (119, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (218, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (211, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (446, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (322, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (37, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (44, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (467, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (463, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (223, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (166, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (497, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (153, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (384, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (139, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (259, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (462, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (474, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (263, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (200, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (263, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (422, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (25, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (498, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (402, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (106, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (415, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (217, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (389, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (52, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (343, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (241, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (105, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (478, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (371, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (264, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (467, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (257, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (305, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (320, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (127, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (314, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (371, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (337, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (360, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (304, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (163, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (195, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (247, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (266, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (334, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (329, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (26, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (457, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (403, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (319, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (2, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (388, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (36, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (168, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (62, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (390, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (146, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (488, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (201, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (50, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (404, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (459, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (12, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (174, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (283, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (379, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (220, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (362, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (216, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (333, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (493, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (249, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (51, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (366, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (188, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (114, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (361, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (149, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (218, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (123, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (307, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (463, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (183, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (350, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (349, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (5, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (231, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (10, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (409, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (134, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (140, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (301, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (432, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (91, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (4, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (244, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (334, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (452, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (310, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (317, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (204, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (38, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (46, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (241, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (440, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (49, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (425, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (137, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (154, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (394, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (21, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (141, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (298, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (122, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (175, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (162, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (36, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (404, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (276, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (42, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (135, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (203, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (105, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (9, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (239, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (19, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (147, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (35, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (32, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (299, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (102, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (142, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (100, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (425, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (102, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (35, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (211, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (482, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (291, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (241, 'Parking');
insert into Hotel_facility (hotelID, facilities) values (275, 'Aircooling');
insert into Hotel_facility (hotelID, facilities) values (410, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (379, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (324, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (154, 'Daily Cleaning');
insert into Hotel_facility (hotelID, facilities) values (29, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (443, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (101, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (299, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (248, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (422, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (223, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (85, 'Sports Area');
insert into Hotel_facility (hotelID, facilities) values (343, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (22, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (435, 'Swimming Pool');
insert into Hotel_facility (hotelID, facilities) values (463, 'Room service');
insert into Hotel_facility (hotelID, facilities) values (98, 'Fitness Center');
insert into Hotel_facility (hotelID, facilities) values (340, '24-hour Reception');
insert into Hotel_facility (hotelID, facilities) values (13, 'Sports Area');
