create table Hotel (
                       hotelId INT,
                       name VARCHAR(66),
                       street VARCHAR(50),
                       zipcode VARCHAR(50),
                       city VARCHAR(50),
                       country VARCHAR(50),
                       rating VARCHAR(1),
                       primary key(hotelID)
);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (1, 'Ascend Resort Collection', 'Sutherland', null, 'Jiubao', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (2, 'America''s Best Value Inn', 'Morrow', '3870-207', 'Pardelhas', 'Portugal', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (3, 'Best Western University Inn & Suites', 'Eagan', 'H9G', 'Lillooet', 'Canada', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (4, 'Holiday Inn Express & Suites Austin South', 'Sage', null, 'Sanqu', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (5, 'Extended Stay America - Atlanta - Perimeter - Hammond Drive', 'Ohio', null, 'Huagai', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (6, 'Americas Best Value Inn-corpus Christi North/airport', 'Banding', '763 32', 'Nedašov', 'Czech Republic', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (7, 'The Troubadour Hotel New Orleans', 'Alpine', '66110', 'Taphan Hin', 'Thailand', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (8, 'Hampton Inn-janesville', 'Di Loreto', null, 'Shuiyuan', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (9, 'Holiday Inn Express Suites Clinton', 'Anderson', '2430', 'Lunec', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (10, 'Candlewood Suites Orange County/Irvine East', 'Bellgrove', null, 'Yunga', 'Peru', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (11, 'The Westin San Diego Gaslamp Quarter', 'Corben', null, 'Pakusari', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (12, 'NOPSI Hotel New Orleans', 'Mallory', '51005', 'Ceuta', 'Spain', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (13, 'Best Western Lake Conroe Inn', 'Graedel', null, 'Vanadzor', 'Armenia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (14, 'Hyatt House Seattle/Downtown', 'Mayer', '30171', 'Venustiano Carranza', 'Mexico', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (15, 'Home2 Suites By Hilton Philadelphia-Convention Center', 'Melvin', null, 'Zhengcun', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (16, 'Villa Paradiso', 'Westend', null, 'Chitungwiza', 'Zimbabwe', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (17, 'Super 8-el Centro', 'Bluestem', null, 'Linhu', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (18, 'Hilton Garden Inn Edison/Raritan Center', 'Towne', '742 73', 'Veřovice', 'Czech Republic', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (19, 'Quality Inn & Suites Nj State Capital Area', 'Swallow', null, 'Šipovo', 'Bosnia and Herzegovina', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (20, 'Economy Inn Suites', 'American Ash', '53085 CEDEX 9', 'Laval', 'France', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (21, 'Hampton Inn Middletown', 'Bunting', null, 'Tseel', 'Mongolia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (22, 'Westgate Inn & Suites', 'Tony', '140074', 'Lyubertsy', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (23, 'Drury Inn & Suites Charlotte Northlake', 'Hayes', null, 'Anju', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (24, 'Candlewood Suites Somerset', 'Green Ridge', null, 'Owando', 'Republic of the Congo', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (25, 'Home2 Suites by Hilton Baltimore Downtown', 'Monument', null, 'Cigenca', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (26, 'Courtyard Las Vegas Henderson/Green Valley', 'Orin', null, 'Copa', 'Peru', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (27, 'Best Western Mulberry Hotel', 'Warbler', null, 'Langqi', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (28, 'Hampton Inn Potomac Mills/Woodbridge', 'Hovde', '59360-000', 'Parelhas', 'Brazil', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (29, 'Ascend Resort Collection', 'Park Meadow', null, 'Jinzhuang', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (30, 'Oak Tree Inn', 'Express', null, 'Wuning', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (31, 'Hampton Inn & Suites Philadelphia Montgomeryville', 'Colorado', null, 'Curahkalak Tengah', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (32, 'BW Premier Collection', 'Rutledge', '7305', 'Tiglauigan', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (33, 'Dover Inn', 'Logan', null, 'Nioumamilima', 'Comoros', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (34, 'Riverside Inn', 'Trailsway', '475038', 'Plato', 'Colombia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (35, 'Orlando Continental Plaza Hotel', 'Namekagon', '4960-160', 'Lage', 'Portugal', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (36, 'Best Western Plus Wilmington/Carolina Beach', 'Montana', null, 'Kebonkalapa', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (37, 'Chalet Motel', 'Miller', '7406', 'General La Madrid', 'Argentina', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (38, 'Courtyard by Marriott Newport News Airport', 'Luster', null, 'Kakhovka', 'Ukraine', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (39, 'Best Western Plus Lockport Hotel', 'Vera', null, 'Wangqu', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (40, 'Best Western Plus Arroyo Roble Hotel & Creekside Villas', 'Anderson', '95113', 'San Jose', 'United States', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (41, 'Baymont Inn & Suites Bowling Green', 'Alpine', '1018', 'Port Area', 'Philippines', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (42, 'Hollywood Motel', 'Steensland', null, 'Banraeaba Village', 'Kiribati', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (43, 'America''s Best Inn Suites', 'Anhalt', '612412', 'Zuyevka', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (44, 'French Quarter Suites Hotel', 'Dovetail', null, 'Kyŏngsŏng', 'North Korea', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (45, 'Carter Lodge', 'Farmco', null, 'Fatumnasi', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (46, 'Hollywood Motel', 'Westerfield', null, 'Heqian', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (47, 'Ramada Louisville Expo Center', 'Service', null, 'Krajan Dua Dawuan Wetan', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (48, 'Home2 Suites by Hilton Baltimore Downtown', 'Red Cloud', '7000', 'Tandil', 'Argentina', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (49, 'Basecamp Hotel', 'Golden Leaf', '6403', 'Lope de Vega', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (50, 'Beacon Hill Hotel and Bistro', 'Butternut', '75200', 'El Calvario', 'Mexico', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (51, 'Sleep Inn', 'Holmberg', '619001', 'Kudymkar', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (52, 'Comfort Suites Outlet Center', 'Oak', '6344', 'Sandayong Sur', 'Philippines', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (53, 'Hampton Inn & Suites Bend', 'Kenwood', '155381', 'Meget', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (54, 'Hampton Inn & Suites Denver Ap Gateway Park', 'Chinook', '346020', 'Krechevitsy', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (55, 'Desert Lodge', '8th', '12008', 'Sibinal', 'Guatemala', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (56, 'Red Roof Inn Cleveland-medina', 'Gale', null, 'Norak', 'Tajikistan', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (57, 'Fairfield Inn and Suites by Marriott Virginia Beach Oceanfront', 'Harbort', null, 'Bukama', 'Democratic Republic of the Congo', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (58, 'Hotel St. Augustine', 'Chive', '5605', 'Bongued', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (59, 'Comfort Inn & Suites West', 'Dapin', null, 'Xinmatou', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (60, 'The Boxer', 'Nelson', '35213', 'Telde', 'Spain', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (61, 'Red Roof Inn & Suites Dekalb', 'Fuller', null, 'Shanxiahu', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (62, 'Hampton Inn & Suites Wilmington Christiana', 'Amoth', '5604', 'Békéscsaba', 'Hungary', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (63, 'Best Western Inn At Palm Springs', 'Cody', null, 'Viengxay', 'Laos', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (64, 'DoubleTree by Hilton Hotel Metropolitan - New York City', 'Prairie Rose', '4006', 'Pangantocan', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (65, 'Hampton Inn and Suites Napa', 'South', '269 42', 'Båstad', 'Sweden', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (66, 'Heritage Suites', 'Mendota', '67-415', 'Kolsko', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (67, 'Pakalana Inn', 'Kinsman', null, 'Kuaidamao', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (68, 'Best Western Plus Arroyo Roble Hotel & Creekside Villas', 'Toban', null, 'Dongyuan', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (69, 'Holiday Inn Express Suites Fort Worth Downtown', 'Fremont', null, 'Qarah Ẕīā’ od Dīn', 'Iran', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (70, 'Hampton Inn and Suites Baltimore Inner Harbor', 'Armistice', '16005', 'Tamahú', 'Guatemala', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (71, 'Comfort Suites-dodge City', 'Trailsway', '23206', 'Sukošan', 'Croatia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (72, 'Red Roof Inn & Suites Dekalb', 'Pawling', '2600', 'Klerksdorp', 'South Africa', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (73, 'Comfort Suites Suffolk - Chesapeake', 'Barnett', null, 'Xiabaishi', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (74, 'Holiday Inn Express Suites Clinton', 'Bashford', '60006 CEDEX', 'Beauvais', 'France', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (75, 'Best Western Plus Glenview-Chicagoland Inn Suites', 'Sheridan', '250 65', 'Líbeznice', 'Czech Republic', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (76, 'The St. Regis Atlanta', 'Gina', '97640', 'Sada', 'Mayotte', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (77, 'Bougainvillea On The Beach', 'Arrowood', null, 'Mazra‘at Bayt Jinn', 'Syria', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (78, 'French Quarter Suites Hotel', 'Bunker Hill', '962-0042', 'Ina', 'Japan', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (79, 'The Boxer', 'Meadow Vale', 'M3H', 'Delaware', 'Canada', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (80, 'EconoLodge', 'Marcy', '10081 CEDEX', 'Troyes', 'France', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (81, 'Comfort Inn-lehigh Valley West', 'Pleasure', null, 'Gowa', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (82, 'SpringHill Suites Coeur d''Alene', 'Hoffman', null, 'Yancheng', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (83, 'Hotel Sausalito', 'Scott', '21604 CEDEX', 'Longvic', 'France', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (84, 'Staybridge Suites Omaha 80th And Dodge', 'West', null, 'Jingzhuang', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (85, 'Residence Inn Seattle Downtown/Lake Union', 'Shoshone', 'G5R', 'Rivière-du-Loup', 'Canada', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (86, 'Residence Inn Seattle Downtown/Lake Union', 'Lakewood', '588 45', 'Dolní Cerekev', 'Czech Republic', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (87, 'Royal Resort', 'Johnson', null, 'Meixian', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (88, 'Red Roof Inn & Suites Dekalb', 'Vera', '59990-000', 'Armação', 'Brazil', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (89, 'Omni Royal Orleans', 'Lotheville', null, 'Ambohitrolomahitsy', 'Madagascar', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (90, 'Extended Stay America - Atlanta - Perimeter - Hammond Drive', 'Mendota', null, 'Titao', 'Burkina Faso', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (91, 'Courtyard by Marriott Newport News Airport', 'Lillian', null, 'Mojo', 'Ethiopia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (92, 'Candlewood Suites Somerset', 'Park Meadow', '75038 CEDEX 01', 'Paris 01', 'France', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (93, 'Carter Lodge', 'Maywood', '79570-000', 'Aparecida do Taboado', 'Brazil', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (94, 'Red Roof Inn Detroit - Southfield', 'Norway Maple', null, 'Baltasar Brum', 'Uruguay', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (95, 'The Charlesmark Hotel', 'Everett', null, 'Weda', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (96, 'Seacrest Oceanfront Hotel', 'Heath', '6328', 'Calape', 'Philippines', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (97, 'Days Inn Apple Valley Sevierville', 'Southridge', '18-230', 'Ciechanowiec', 'Poland', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (98, 'Motel 6 Grand Rapids - Airport', 'Burning Wood', null, 'Chahe', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (99, 'Hotel Sutter', 'Ronald Regan', '523068', 'Iles', 'Colombia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (100, 'Copperleaf Hotel', 'Monterey', null, 'Banjarsari', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (101, 'W Austin', 'Towne', '57-220', 'Ziębice', 'Poland', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (102, 'Hampton Inn-janesville', 'Commercial', '88300-000', 'Itajaí', 'Brazil', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (103, 'Bricco Suites', 'Colorado', null, 'Jincheng', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (104, 'Courtyard by Marriott Newport News Airport', 'Eggendart', null, 'Lhokkruet', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (105, 'Royal Resort', 'Holmberg', '2050-065', 'Aveiras de Cima', 'Portugal', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (106, 'The Troubadour Hotel New Orleans', 'Village Green', '2640-394', 'Mafra', 'Portugal', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (107, 'The Inn at Solvang', 'Westport', null, 'Huangli', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (108, 'Soniat House', 'Sycamore', null, 'Bayan Qagan', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (109, 'The Beekman', 'Dahle', null, 'Cikalang', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (110, 'Motel 6 Grand Rapids - Airport', 'Kenwood', '42055 CEDEX 2', 'Saint-Étienne', 'France', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (111, 'Snowshoe Motel', 'Warbler', null, 'Shinaihai', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (112, 'Holiday Inn Express & Suites Baton Rouge East', 'Fisk', null, 'Moyo', 'Uganda', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (113, 'The Westin San Diego Gaslamp Quarter', 'Hazelcrest', null, 'Pingtan', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (114, 'Holiday Inn Express Alpharetta - Roswell', 'Meadow Vale', '3525-254', 'Póvoa de Santo António', 'Portugal', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (115, 'Wingate by Wyndham San Marcos', 'Moulton', '37-522', 'Wiązownica', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (116, 'Indigo Inn', 'David', '96-315', 'Wiskitki', 'Poland', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (117, 'Econo Lodge', 'Mandrake', null, 'Cibatu', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (118, 'Hampton Inn-seattle/everett', 'Bartelt', null, 'Berlín', 'Honduras', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (119, 'Hampton Inn & Suites Philadelphia Montgomeryville', 'Di Loreto', null, 'Chervone', 'Ukraine', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (120, 'Courtyard Charlottesville North', 'Toban', null, 'Yousheng', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (121, 'The Academy Hotel Colorado Springs', 'Londonderry', null, 'Akhaldaba', 'Georgia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (122, 'Bluegreen Vacations Patrick Henry Sqr', 'Hovde', null, 'Hammam Sousse', 'Tunisia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (123, 'Island View Motel', 'Bay', null, 'Krajan Srigonco', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (124, 'The Lodge At Russell', 'Bonner', null, 'Tadjoura', 'Djibouti', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (125, 'Ascend Resort Collection', 'Gina', '3311', 'Mabay', 'Philippines', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (126, 'Best Western Seven Seas', 'Chinook', null, 'Darhan', 'Mongolia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (127, 'The Parkside Inn', 'Ludington', null, 'Baimaqiao', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (128, 'Hilton Garden Inn Winchester', 'Bunker Hill', null, 'San Ignacio', 'Honduras', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (129, 'TownePlace Suites Anaheim Maingate Near Angel Stadium', 'Havey', null, 'Maundai', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (130, 'M -37 Motel', 'Westend', null, 'San José de Cusmapa', 'Nicaragua', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (131, 'Hampton Inn & Suites St. Louis/South I-55', 'Dapin', null, 'Were', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (132, 'Home2 Suites by Hilton Baltimore Downtown', 'Gerald', null, 'Yaguachi Nuevo', 'Ecuador', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (133, 'Drury Inn St Louis Collinsville', 'Morrow', '63-304', 'Broniszewice', 'Poland', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (134, 'Homewood Suites by Hilton Orlando-Nearest to Univ Studios', 'Schiller', '67-400', 'Wschowa', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (135, 'Drury Inn St Louis Collinsville', 'Continental', null, 'Hangou', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (136, 'Ramada-kingman', 'Dayton', '94170', 'Nong Chik', 'Thailand', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (137, 'Main Street Station Casino Brewery Hotel', 'Sugar', '8336', 'Villa Regina', 'Argentina', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (138, 'Hotel Sausalito', '7th', null, 'Yujia', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (139, 'Hyatt Regency Orlando International Airport', 'Brentwood', null, 'Tengqiao', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (140, 'Courtyard by Marriott Scottsdale Salt River', 'Independence', '645 32', 'Strängnäs', 'Sweden', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (141, 'Best Western Plus Wilmington/Carolina Beach', 'Canary', null, 'Péfki', 'Greece', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (142, 'Seven Gables Inn', 'Main', '2422', 'Taloy', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (143, 'Best Western Plus Heritage Inn Rancho Cucamonga/Ontario', 'Eagle Crest', null, 'Jargalant', 'Mongolia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (144, 'Best Western Courtesy Inn', 'Dryden', '660126', 'Sheregesh', 'Russia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (145, 'Budget Inn', 'Northridge', null, 'Tianhe', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (146, 'Days Inn Apple Valley Sevierville', 'Ronald Regan', null, 'Jinjiang', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (147, 'Best Western Courtesy Inn', 'Meadow Ridge', null, 'Gali', 'Georgia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (148, 'A Waldorf Astoria Hotel', 'Vera', null, 'Oropéndolas', 'Honduras', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (149, 'Best Western Superstition Springs Inn', 'Ramsey', null, 'Batou', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (150, 'Park City Peaks Hotel', 'Heffernan', '467-0862', 'Mombetsu', 'Japan', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (151, 'La Quinta Inn & Suites Corsicana', 'Carberry', '623075', 'Gadzhiyevo', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (152, 'Rancho Tee Motel', 'Scott', '441 63', 'Alingsås', 'Sweden', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (153, 'Motel 6', 'Dwight', '18000', 'Phichit', 'Thailand', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (154, 'Ramada Louisville Expo Center', 'Dennis', null, 'Domoni', 'Comoros', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (155, 'BW Premier Collection', 'Banding', '7450-265', 'Vaiamonte', 'Portugal', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (156, 'Candlewood Suites Orange County/Irvine East', 'Forest', null, 'Linggamanik', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (157, 'Best Western Lake Conroe Inn', 'Lillian', 'BS41', 'Bristol', 'United Kingdom', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (158, 'Wyndham Canterbury at San Francisco', 'Forest Run', null, 'Camilaca', 'Peru', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (159, 'Motel 6 Atlanta Downtown', 'Almo', null, 'Lolayan', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (160, 'Super 8 Delavan Near Lake Geneva', 'Moose', null, 'Zvezdara', 'Serbia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (161, 'Holiday Inn Express & Suites Bethlehem', 'Westridge', null, 'Shijiazhai', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (162, 'Rodeway Inn', 'Washington', '69367 CEDEX 07', 'Lyon', 'France', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (163, 'Extended Stay America - Atlanta - Clairmont', 'Moland', null, 'Glempang Tengah', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (164, 'The Pearl Hotel', 'Melvin', null, 'Oqtosh', 'Uzbekistan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (165, 'Cozy Villa Motel', 'Stang', '739 46', 'Hukvaldy', 'Czech Republic', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (166, 'Best Western Plus Glenview-Chicagoland Inn Suites', 'Luster', null, 'Hongshanyao', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (167, 'The Troubadour Hotel New Orleans', 'Nancy', '45690-000', 'Una', 'Brazil', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (168, 'Inn at El Gaucho', 'Morrow', 'L9H', 'Sundre', 'Canada', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (169, 'The Westin Chicago River North', 'Caliangt', '32245', 'Nijemci', 'Croatia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (170, 'Hyatt Place Atlanta Airport-South', 'Rusk', '95520-000', 'Osório', 'Brazil', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (171, 'DoubleTree by Hilton Hotel Metropolitan - New York City', 'Crowley', null, 'Cape Coast', 'Ghana', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (172, 'Hyatt Place Atlanta Airport-South', 'Summer Ridge', null, 'Lápas', 'Greece', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (173, 'The Resort at Longboat Key Club', 'Armistice', null, 'Trebisht-Muçinë', 'Albania', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (174, 'Ramada-kingman', 'Hoard', '93704', 'Fresno', 'United States', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (175, 'Quality Inn & Suites', 'Rowland', null, 'Banjar Yehsatang', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (176, 'Admiral Hotel', 'Kenwood', '196627', 'Pushkin', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (177, 'Lyttleton Inn', 'Lakewood Gardens', null, 'Panyambungan', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (178, 'Bancroft Hotel', 'Hansons', null, 'Budva', 'Montenegro', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (179, 'Hilton Baltimore BWI Airport', 'Lawn', null, 'Karangcombong', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (180, 'Holiday Inn Express & Suites Lake Placid', 'Muir', null, 'Lianyuan', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (181, 'Extended Stay America - Atlanta - Clairmont', 'Lerdahl', '2621', 'Gabi', 'Philippines', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (182, 'Schweich''s Hotel Bar & Restaurant', 'Westerfield', null, 'Zhangcaizhuang', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (183, 'The Resort at Longboat Key Club', 'Union', null, 'Xiaji', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (184, 'Motel 6', 'Stang', '12530-000', 'Cunha', 'Brazil', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (185, 'Hampton Inn-saco/biddeford', 'Cody', null, 'Sipirok', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (186, 'The Redbury New York', 'Transport', null, 'Hoàn Kiếm', 'Vietnam', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (187, 'Best Western-ashburn Inn', 'Fordem', '62-570', 'Rychwał', 'Poland', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (188, 'McMenamins Kennedy School', 'Judy', null, 'Caidian', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (189, 'Americas Best Value Inn-corpus Christi North/airport', 'Lakeland', '4712', 'Bolo', 'Philippines', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (190, 'Super 8 Delavan Near Lake Geneva', 'Macpherson', null, 'Kepel', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (191, 'WoodSpring Suites Phoenix I-10 West', 'Arkansas', null, 'Aimin', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (192, 'Campus Inn Motel', 'Continental', 'V9A', 'Victoria', 'Canada', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (193, 'Beavers Bend Lodging', 'Ilene', '699-3162', 'Gōtsuchō', 'Japan', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (194, 'Loews Portofino Bay Hotel at Universal Orlando', 'Artisan', null, 'Aryiropoúlion', 'Greece', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (195, 'Days Inn & Suites Milwaukee Airport', 'Continental', '891-0704', 'Beppu', 'Japan', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (196, 'Best Western Tomah Hotel', 'Farragut', null, 'Duqiong', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (197, 'Hampton Inn-athens', 'Crest Line', null, 'Tandaltī', 'Sudan', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (198, 'Lincoln Plaza Hotel', 'Rusk', '44160', 'Chiang Yuen', 'Thailand', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (199, 'Courtyard by Marriott Scottsdale Salt River', 'Thackeray', null, 'El Corozo', 'Venezuela', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (200, 'Westchester Hotel', 'Fair Oaks', '174442', 'Opechenskiy Posad', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (201, 'Sterling Gardens Hotel', 'Dryden', '252 44', 'Psáry', 'Czech Republic', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (202, 'Sea-Aire Motel', 'Harbort', '613110', 'Vakhrushi', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (203, 'Hampton Inn & Suites Philadelphia Montgomeryville', 'Vera', '384 72', 'Zdíkov', 'Czech Republic', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (204, 'Budget Inn', 'Northwestern', null, 'Pomahuaca', 'Peru', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (205, 'Island Country Inn', 'Northport', '6404', 'Tinampo', 'Philippines', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (206, 'Aloft Cleveland Downtown', 'Express', null, 'Damaturu', 'Nigeria', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (207, 'McMenamins Kennedy School', 'Redwing', '38-300', 'Złotniki', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (208, 'Hampton Inn & Suites Denver Ap Gateway Park', 'Barnett', '76420-000', 'Niquelândia', 'Brazil', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (209, 'Homewood Suites By Hilton Lancaster', 'Hooker', '46-113', 'Wilków', 'Poland', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (210, 'Dolphin Key Resort', 'Roxbury', null, 'Tiouli', 'Morocco', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (211, 'Westchester Hotel', 'Nova', null, 'Huanchaco', 'Peru', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (212, 'Embassy Suites by Hilton Boston at Logan Airport', 'Rockefeller', null, 'Cuenca', 'Peru', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (213, 'Maison de Macarty', 'Lunder', null, 'Shuangmiaojie', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (214, 'AC Hotel Miami Beach', 'Lotheville', '53401', 'Choa Saidān Shāh', 'Pakistan', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (215, 'La Quinta Inn & Suites Corsicana', 'Bonner', '363503', 'Chikola', 'Russia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (216, 'Pike Motel', 'Anthes', null, 'Hongling', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (217, 'Hollywood Motel', 'Barby', null, 'Rahayu Dua', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (218, 'Auburn Travelodge Inn & Suites', 'Hagan', null, 'Xylókastro', 'Greece', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (219, 'Ramada Plaza Hawthorne/LAX', 'Garrison', null, 'Bāft', 'Iran', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (220, 'Mainstay Suites-fort Campbell', 'Warrior', '6324', 'Lunas', 'Philippines', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (221, 'Sheraton Portland Airport Hotel', 'Melrose', '855058', 'Sabanalarga', 'Colombia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (222, 'The Charlesmark Hotel', 'Summerview', '249026', 'Yermolino', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (223, 'La Quinta Inn Suites Warner Robins - Robins AFB', 'Hintze', null, 'Cicurug', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (224, 'The L.A. Hotel Downtown', 'Southridge', null, 'Sukarama', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (225, 'Homewood Suites by Hilton Austin Arboretum / NW', 'Memorial', '73190', 'Oklahoma City', 'United States', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (226, 'Holiday Inn Express Suites Fort Worth Downtown', 'Riverside', '9814', 'Bluff', 'New Zealand', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (227, 'Candlewood Suites Somerset', 'Buhler', null, 'El Socorro', 'Honduras', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (228, 'Wingate by Wyndham San Marcos', 'Chinook', null, 'Anār Darah', 'Afghanistan', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (229, 'Holiday Inn Express and Suites', 'Rockefeller', '2661', 'Kruisfontein', 'South Africa', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (230, 'Pa', 'Twin Pines', '371-0858', 'Kanekomachi', 'Japan', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (231, 'University Inn Corvallis', 'Graceland', null, 'Sumberkemuning', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (232, 'AC Hotel by Marriott Boston Downtown', 'Oakridge', '1808', 'Nangka', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (233, 'Hotel Prince Spafford', 'Scott', '10184', 'New York City', 'United States', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (234, 'Holiday Inn North Phoenix', 'Meadow Valley', '17690-000', 'Bastos', 'Brazil', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (235, 'Tapestry Collection by Hilton', 'Nancy', '4780-166', 'Santa Cristina Couto', 'Portugal', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (236, 'Residence Inn San Diego Central', 'Vidon', null, 'Xiaolan', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (237, 'Drury Inn St Louis Collinsville', 'Kings', null, 'Tuodian', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (238, 'Red Roof Inn Cleveland-medina', 'Meadow Valley', null, 'Yaogou', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (239, 'Wingate by Wyndham Frisco', 'Loftsgordon', '64-810', 'Kaczory', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (240, 'Riverside Inn', 'Hudson', null, 'Beyla', 'Guinea', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (241, 'Appletree Inn', 'Ohio', null, 'Kayu Agung', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (242, 'Courtyard by Marriott Houston Brookhollow', 'Lillian', null, 'Kampungladang', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (243, 'Fairway Inn', 'Towne', null, 'Longquan', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (244, 'Best Western Seven Seas', 'Fairfield', null, 'Sagua la Grande', 'Cuba', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (245, 'Hampton Inn-elkhorn', 'Algoma', null, 'Juxing', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (246, 'Hollywood Motel', 'Utah', null, 'Slavuta', 'Ukraine', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (247, 'Best Western Springfield', 'Portage', null, 'Kunmi Erdi', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (248, 'Budget Inn', 'Esker', '373 41', 'Hluboká nad Vltavou', 'Czech Republic', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (249, 'Hyatt House Seattle/Downtown', 'Morningstar', '521529', 'La Unión', 'Colombia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (250, 'Hyatt Place Atlanta Airport-South', 'Coolidge', null, 'Buda-Kashalyova', 'Belarus', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (251, 'Pa', 'Northridge', 'R32', 'Muff', 'Ireland', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (252, 'Bay Pointe Inn Restaurant', 'Gulseth', '18870-000', 'Fartura', 'Brazil', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (253, 'Rodeway Inn San Diego Near Qualcomm Stadium', 'Killdeer', null, 'Xiangshan', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (254, 'Hampton Inn Union City', 'Southridge', null, 'Magburaka', 'Sierra Leone', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (255, 'Drury Inn & Suites Atlanta Airport', 'Mallard', null, 'Leramatang', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (256, 'Residence Inn Chicago Deerfield', 'Mallory', '57005', 'Kėdainiai', 'Lithuania', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (257, 'Arizona Mountain Inn & Cabins', 'Cascade', '8508', 'La Paz', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (258, 'Hampton Inn & Suites Dodge City', 'Toban', '5184', 'Capilla del Monte', 'Argentina', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (259, 'Best Western Plus Stevenson Manor', 'Towne', null, 'Lawepakam', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (260, 'Residence Inn San Diego Central', 'Bonner', null, 'Tebluru', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (261, 'Best Western Plus Encina Inn & Suites', 'Bashford', null, 'Yacheng', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (262, 'Courtyard by Marriott Houston Brookhollow', 'Vahlen', null, 'Memaliaj', 'Albania', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (263, 'A Rosewood Hotel', 'Veith', '3181', 'Pampa de los Guanacos', 'Argentina', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (264, 'Fairfield Inn Corbin', '2nd', null, 'Tianxin', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (265, 'Hilton Garden Inn Williamsburg', 'Crownhardt', null, 'Taranovskoye', 'Kazakhstan', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (266, 'MOXY New Orleans Downtown/French Quarter Area', 'Jenifer', null, 'Ílion', 'Greece', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (267, 'Hampton Inn Union City', 'Randy', null, 'Lobuni', 'Ethiopia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (268, 'The Villa Toscana', 'Hagan', null, 'Ágios Pétros', 'Greece', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (269, 'Orlando Continental Plaza Hotel', 'Mitchell', '547079', 'El Carmen', 'Colombia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (270, 'The Pearl Hotel', 'Scoville', null, 'Boli', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (271, 'Inn at El Gaucho', 'Delaware', null, 'Tongquan', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (272, 'Sleep Inn', 'Northridge', null, 'Rozsypne', 'Ukraine', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (273, 'Motel 6', 'Ridgeway', '6550', 'Tres Arroyos', 'Argentina', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (274, 'Best Western Plus Hotel At The Convention Center', '3rd', '453679', 'Severobaykal’sk', 'Russia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (275, 'Drury Inn Suites St. Louis Convention Center', 'Little Fleur', '133567', 'Regidor', 'Colombia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (276, 'Quality Inn and Suites By The Parks', 'Summer Ridge', '366101', 'Grebenskaya', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (277, 'Extended Stay America - Atlanta - Perimeter - Hammond Drive', 'Norway Maple', null, 'Nanfeng', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (278, 'Comfort Inn I-10 West at 51st Ave', 'Independence', '5130-065', 'Ervedosa do Douro', 'Portugal', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (279, 'Travelodge-beckley', 'Loeprich', '666330', 'Tyret’ Pervaya', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (280, 'Aqua Soleil Hotel And Mineral Water Spa', 'Bashford', null, 'Shigongqiao', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (281, 'Chelsea Savoy Hotel', 'Golf Course', null, 'Tarata', 'Peru', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (282, 'Tapestry Collection by Hilton', 'Glacier Hill', null, 'Huangzhai', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (283, 'Aloft Arundel Mills', 'Luster', '20147', 'Milano', 'Italy', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (284, 'Hotel Del Flores', 'Sage', '27-630', 'Zawichost', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (285, 'The Parkside Inn', 'Gina', null, 'Sharga', 'Mongolia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (286, 'Candlewood Suites Orange County/Irvine East', 'Fairfield', '62-045', 'Pniewy', 'Poland', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (287, 'Hyatt House Parsippany/Whippany', 'Oakridge', null, 'Sumberrejo', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (288, 'Staybridge Suites El Paso Airport Area', 'Service', 'OX12', 'Charlton', 'United Kingdom', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (289, 'Holiday Inn Express & Suites Baton Rouge East', 'Maple Wood', null, 'Kafr Thulth', 'Palestinian Territory', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (290, 'Westchester Hotel', 'Jackson', '69200', 'San Sebastian', 'Mexico', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (291, 'Econo Lodge', 'Sunfield', null, 'Cipeundeuy', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (292, 'Solvang Inn Cottages', 'Maryland', '396180', 'Pereleshino', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (293, 'Hilton Garden Inn Winchester', 'American', null, 'Waru', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (294, 'Hyatt Regency Sacramento', 'Cottonwood', '06854', 'Norwalk', 'United States', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (295, 'Flamingo Inn Rosemead', 'Pankratz', null, 'Káto Dhiminió', 'Greece', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (296, 'The Pearl Hotel', 'Kinsman', null, 'Táriba', 'Venezuela', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (297, 'Garrison Inn', 'Coolidge', null, 'Şirvan', 'Azerbaijan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (298, 'Hampton Inn-athens', 'Eagle Crest', null, 'Waina', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (299, 'Days Inn & Suites Milwaukee Airport', 'Westend', null, 'Balzar', 'Ecuador', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (300, 'Best Western Kenosha Inn', 'Kennedy', null, 'Kutum', 'Sudan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (301, 'Americas Best Value Inn-rialto', 'Hollow Ridge', null, 'Yeni Suraxanı', 'Azerbaijan', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (302, 'Homewood Suites by Hilton Austin Arboretum / NW', 'Sage', '184 34', 'Åkersberga', 'Sweden', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (303, 'Bancroft Hotel', 'Mesta', null, 'Huayana', 'Peru', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (304, 'Drury Inn & Suites Charlotte Northlake', 'Eggendart', '3009', 'Rotterdam postbusnummers', 'Netherlands', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (305, 'MOXY New Orleans Downtown/French Quarter Area', 'Thackeray', null, 'Jatiklampok', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (306, 'Coconut Waikiki Hotel', 'Mosinee', null, 'Balai', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (307, 'EconoLodge', 'La Follette', null, 'Mekarsari', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (308, 'Comfort Inn-lehigh Valley West', 'Milwaukee', null, 'Makanya', 'Tanzania', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (309, 'Holiday Inn Express Washington Dc Sw - Springfield', 'Waubesa', null, 'Al Majāridah', 'Saudi Arabia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (310, 'Econo Lodge', 'Cambridge', '13270', 'Bang Sai', 'Thailand', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (311, 'Snowshoe Motel', 'Gina', null, 'Kafir Qala', 'Afghanistan', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (312, 'Hotel Storyville', 'Westridge', '1427', 'Sugcad', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (313, 'Best Western Plus Heritage Inn Rancho Cucamonga/Ontario', 'Mayfield', '7479', 'Trondheim', 'Norway', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (314, 'Best Western-valencia Inn', 'Donald', '35167-000', 'Santana do Paraíso', 'Brazil', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (315, 'Whispering Woods Resort', 'Lunder', '1000', 'Sofia', 'Bulgaria', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (316, 'Quality Inn and Suites By The Parks', 'Hoffman', null, 'Montijo', 'Panama', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (317, 'Hotel Sutter', 'Ronald Regan', '3870-207', 'Pardelhas', 'Portugal', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (318, 'The Hotel of South Beach', 'Fulton', '347-0105', 'Kisai', 'Japan', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (319, 'TownePlace Suites by Marriott Suffolk Chesapeake', 'Claremont', '346536', 'Talovyy', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (320, 'Historic Hotel Bethlehem', 'Superior', '1079', 'Amsterdam Oud Zuid en Rivierenbuurt', 'Netherlands', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (321, 'Omni Royal Orleans', 'Fieldstone', '85260', 'Scottsdale', 'United States', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (322, 'Hotel Zelos', 'Washington', '4770-565', 'Vale de São Cosme', 'Portugal', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (323, 'Oak Tree Inn', 'Eastlawn', null, 'Qinghe', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (324, 'Campus Inn Motel', 'Lotheville', null, 'Paita', 'Peru', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (325, 'Best Western-ashburn Inn', 'Cambridge', null, 'Jiamaogong', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (326, 'Beacon Hill Hotel and Bistro', 'Dovetail', '4620-620', 'Quintães', 'Portugal', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (327, 'Sleep Inn', 'Lillian', null, 'Suwon-si', 'South Korea', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (328, 'Pacific Shores Inn', 'Northport', null, 'Calbuco', 'Chile', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (329, 'Tradewinds Restaurant', 'Annamark', '415088', 'La Argentina', 'Colombia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (330, 'Days Inn Baltimore South/Glen Burnie', 'Oakridge', '412-0048', 'Gotemba', 'Japan', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (331, 'Hampton Inn Suites National HarborAlexandria Area', 'Hayes', null, 'Dongshi', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (332, 'Best Western Plus Arroyo Roble Hotel & Creekside Villas', 'Muir', '1802', 'Frederiksberg', 'Denmark', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (333, 'Hotel 502', 'Ramsey', null, 'Xiongshan', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (334, 'Copperleaf Hotel', 'Doe Crossing', '2870-005', 'Montijo', 'Portugal', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (335, 'Best Western Springfield West Inn', 'Forest', null, 'Ayapa', 'Honduras', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (336, 'Econo Lodge', 'Quincy', null, 'Huangqu', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (337, 'The Chateau Motel', 'Twin Pines', null, 'Sukamulya', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (338, 'SpringHill Suites by Marriott Virginia Beach Oceanfront', 'Oxford', null, 'Pancoran', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (339, 'Best Western Plus Encina Inn & Suites', 'Heath', '891-0704', 'Beppu', 'Japan', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (340, 'Colony Hotel', 'Logan', null, 'Stony Hill', 'Jamaica', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (341, 'Candlewood Suites Somerset', 'Logan', '64800-000', 'Floriano', 'Brazil', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (342, 'Appletree Inn', 'Sugar', '93726', 'Fresno', 'United States', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (343, 'Desert Inn Motel', 'Merrick', null, 'Sihe', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (344, 'Coconut Waikiki Hotel', 'Dennis', null, 'Liufeng', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (345, 'Best Western Plus Hotel At The Convention Center', 'Jenna', '3706', 'Mabua', 'Philippines', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (346, 'AC Hotel by Marriott Boston Downtown', 'Prairie Rose', '8037', 'Zürich', 'Switzerland', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (347, 'Hilton Garden Inn Bettendorf/quad Cities', 'Anhalt', '663490', 'Kodinsk', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (348, 'Best Western Plus Chalmette Hotel', 'Bunker Hill', null, 'Rafael Perazza', 'Uruguay', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (349, 'Motel 6', 'Orin', '19880-000', 'Cândido Mota', 'Brazil', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (350, 'AC Hotel Miami Beach', 'Lake View', '397473', 'Novaya Chigla', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (351, 'Top''s Motel', 'Nobel', '8421', 'San Isidro', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (352, 'Rancho Valencia Resort Spa', 'Dixon', null, 'El Carmen', 'Peru', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (353, 'American Inn', 'Moland', '5417', 'Sagud-Bahley', 'Philippines', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (354, 'Hampton Inn & Suites Brookings', 'Cordelia', '10600', 'Kolonnawa', 'Sri Lanka', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (355, 'Alpine Motel', 'Prairie Rose', '3720-546', 'Quintã', 'Portugal', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (356, 'Embassy Suites by Hilton Philadelphia - Center City', 'Barnett', '10805', 'Ipís', 'Costa Rica', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (357, 'Hyatt Regency Grand Cypress', 'Monterey', null, 'Talca', 'Chile', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (358, 'Super 8 Delavan Near Lake Geneva', 'Farwell', null, 'Mamfe', 'Cameroon', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (359, 'Hotel Sutter', 'Emmet', null, 'Anling', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (360, 'Fairfield Inn Tracy', 'Oriole', '31210', 'Progreso', 'Mexico', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (361, 'America''s Best Inn Suites', 'Talmadge', null, 'Shatian', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (362, 'Rodeway Inn Boardwalk', 'Old Gate', null, 'Jianxincun', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (363, 'Residence Inn Springfield South', 'Maple', '11480', 'Jamaica', 'United States', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (364, 'Seacrest Oceanfront Hotel', 'Elgar', '4950-703', 'Carvalho', 'Portugal', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (365, 'BEST WESTERN Garden Inn', 'Walton', '368117', 'Dubki', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (366, 'Rancho Valencia Resort Spa', 'Meadow Vale', null, 'Verkhnyachka', 'Ukraine', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (367, 'Eden Roc Inn & Suites', 'Karstens', 'H1V', 'Summerland', 'Canada', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (368, 'Best Western Plus Chalmette Hotel', 'Bobwhite', '135 40', 'Tyresö', 'Sweden', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (369, 'Plaza Motel', 'Dayton', null, 'Cigemlong', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (370, 'Bay Pointe Inn Restaurant', 'Fremont', '190', 'Vogar', 'Iceland', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (371, 'Fairfield Inn Corbin', 'Dunning', null, 'Robatal', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (372, 'Budget Inn', 'Knutson', null, 'Ciherang', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (373, 'Hilton Garden Inn Winchester', 'Porter', '93604 CEDEX', 'Aulnay-sous-Bois', 'France', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (374, 'Holiday Inn Express Albuquerque (I-40 Eubank)', 'Park Meadow', null, 'Haocun', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (375, 'The Bertram Inn & Conference Center', 'Graedel', null, 'Lipu', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (376, 'Rodeway Inn Oceanview', 'Loeprich', '9913', 'Trompsburg', 'South Africa', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (377, 'Hampton Inn-athens', 'Corben', '442895', 'Serdobsk', 'Russia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (378, 'Holiday Inn Express & Suites Bethlehem', 'Division', null, 'Évosmos', 'Greece', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (379, 'W Austin', 'Cascade', null, 'Tarakaniv', 'Ukraine', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (380, 'Travelodge-beckley', 'South', '1761', 'Pontevedra', 'Argentina', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (381, 'The Lodge At Russell', 'Muir', '03006 CEDEX', 'Moulins', 'France', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (382, 'Drury Inn Suites St. Louis Convention Center', 'Lillian', '31407', 'Ipoh', 'Malaysia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (383, 'MacRae''s Of Homosassa Inc', 'Carberry', null, 'Binzhou', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (384, 'Red Roof Inn Phoenix North - Bell Road', 'Basil', null, 'Koumra', 'Chad', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (385, 'Hotel Lincoln', 'Ridgeview', null, 'Qal‘ah-ye Kūf', 'Afghanistan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (386, 'Hampton Inn & Suites Jackson', 'Meadow Valley', null, 'Nevyts’ke', 'Ukraine', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (387, 'Century Hotel', 'Oneill', '7160-208', 'Vila Viçosa', 'Portugal', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (388, 'Comfort Suites-elgin', 'Florence', '2730-077', 'Valejas', 'Portugal', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (389, 'Holiday Inn Express & Suites Sioux Falls Southwest', 'Alpine', '3107', 'Laya', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (390, 'Hilton Garden Inn Chesapeake/Suffolk', 'Sage', null, 'Baumata', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (391, 'Super 8-dover', 'Maple', null, 'Mafa', 'Nigeria', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (392, 'Sleep Inn', 'Swallow', null, 'Tsumeb', 'Namibia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (393, 'Rodeway Inn', 'Melody', null, 'Fushë-Muhurr', 'Albania', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (394, 'Hyatt Regency Sacramento', 'Macpherson', '457151', 'Volokonovka', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (395, 'Americas Best Value Inn-corpus Christi North/airport', 'Bay', null, 'Máncora', 'Peru', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (396, 'The Resort at Longboat Key Club', 'Jana', '613155', 'Slobodskoy', 'Russia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (397, 'Pike Motel', 'Barby', null, 'Bhunya', 'Swaziland', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (398, 'Rodeway Inn Oceanview', 'Northview', '949-6212', 'Mikuni', 'Japan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (399, 'Central Loop Hotel', 'Schmedeman', null, 'Purwokerto', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (400, 'Beach Comber Inn', 'Portage', null, 'Cidadap', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (401, 'Halcyon Hotel', 'Stuart', null, 'Dayan', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (402, 'Flamingo Inn Rosemead', 'Northfield', null, 'Tianfen', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (403, 'Motel Del Rogue', 'Anhalt', '36180', 'Khon San', 'Thailand', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (404, 'Staybridge Suites Chantilly Dulles Airport', 'Nancy', '34-735', 'Niedźwiedź', 'Poland', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (405, 'Maison de Macarty', 'Golf View', '24-120', 'Kazimierz Dolny', 'Poland', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (406, 'Holiday Inn Express & Suites Baton Rouge East', 'Center', null, 'Tashang', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (407, 'Hampton Inn Suites Conroe I45 North', 'Fairfield', '51016', 'San Francisco', 'Mexico', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (408, 'The Redbury New York', 'Chive', null, 'Wonocolo', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (409, 'Hotel Sausalito', 'Claremont', '2822', 'Panognawan', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (410, 'Hotel Del Flores', 'Mcguire', null, 'Nokaneng', 'Botswana', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (411, 'Hotel Rose', 'Macpherson', '402 25', 'Göteborg', 'Sweden', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (412, 'Baymont Inn & Suites Bowling Green', 'Marcy', null, 'Dabou', 'Ivory Coast', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (413, 'Best Western Suites Near Opryland', 'Clemons', null, 'Songjianghe', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (414, 'Holiday Inn Express Suites Northwood', 'Pierstorff', null, 'Tiang', 'Indonesia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (415, 'America''s Best Inn Suites', 'Heffernan', '32123', 'Daytona Beach', 'United States', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (416, 'The Annex at The Chelsea', 'Merry', '5602', 'Libacao', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (417, 'TownePlace Suites by Marriott Suffolk Chesapeake', 'Darwin', null, 'Simpang', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (418, 'The Bertram Inn & Conference Center', 'Warbler', '01760', 'Kronoby', 'Finland', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (419, 'Comfort Inn-lehigh Valley West', 'Maywood', null, 'Muraloka', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (420, 'Econolodge', 'Kim', null, 'Modis', 'Indonesia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (421, 'Pakalana Inn', 'Wayridge', null, 'Néa Magnisía', 'Greece', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (422, 'Comfort Suites-dodge City', 'Mcbride', null, 'Youxi', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (423, 'Homewood Suites By Hilton Lancaster', 'Browning', null, 'Aktau', 'Kazakhstan', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (424, 'Best Western Superstition Springs Inn', 'Iowa', '31210', 'Progreso', 'Mexico', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (425, 'Residence Inn By Marriott Waldorf', 'Montana', null, 'Songgui', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (426, 'Copperleaf Hotel', 'Bluestem', '47220', 'Vojnić', 'Croatia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (427, 'Chelsea Savoy Hotel', 'Mariners Cove', '00851', 'Saint Croix', 'U.S. Virgin Islands', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (428, 'Grand Inn', 'Elgar', '3461', 'La Quiaca', 'Argentina', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (429, 'Best Western Inn At Palm Springs', 'Glendale', null, 'Tawun', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (430, 'Dolphin Key Resort', 'Moose', '39-215', 'Czarna', 'Poland', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (431, 'Residence Inn Chicago Bloomingdale', 'Loeprich', null, 'Jichang', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (432, 'Hampton Inn and Suites Williamsburg-Central', 'Eggendart', null, 'Huyang', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (433, 'Holiday Inn Express & Suites Atlanta East - Lithonia', 'Duke', null, 'Yongyang', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (434, 'XV Beacon', 'Brentwood', null, 'Raoshi', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (435, 'Americas Best Value Inn-rialto', 'Gateway', '31210', 'Progreso', 'Mexico', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (436, 'Seven Gables Inn', 'Grim', '632643', 'Kochenëvo', 'Russia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (437, 'Dover Inn', 'Florence', null, 'Gaopi', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (438, 'A Rosewood Hotel', 'Carioca', null, 'Laḩij', 'Yemen', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (439, 'Days Inn Columbus East', 'Moose', '73-220', 'Drawno', 'Poland', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (440, 'Hampton Inn-saco/biddeford', 'Eliot', '361215', 'Urozhaynoye', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (441, 'Comfort Suites', 'Moland', null, 'Kliwon Cibingbin', 'Indonesia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (442, 'Lincoln Plaza Hotel', 'Heffernan', null, 'Dongchen', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (443, 'Red Roof Inn Fresno - Yosemite Gateway', 'Hermina', '151407', 'Chiscas', 'Colombia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (444, 'MOXY New Orleans Downtown/French Quarter Area', 'High Crossing', null, 'Petoa', 'Honduras', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (445, 'Wingate by Wyndham San Marcos', 'Tony', null, 'Dzüünkharaa', 'Mongolia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (446, 'Hampton Inn & Suites Cedar Rapids North', 'Bashford', null, 'Ustupo', 'Panama', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (447, 'Alpine Motel', 'Memorial', null, 'Beishan', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (448, 'Hampton Inn-athens', 'Eastlawn', null, 'Andir', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (449, 'Home2 Suites by Hilton Baltimore Downtown', 'Bowman', '94724', 'La Reforma', 'Mexico', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (450, 'Hilton Garden Inn Myrtle Beach/Coastal Grand Mall', 'Express', null, 'Dongjiao', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (451, 'Pier 5 Hotel Baltimore', 'Maywood', null, 'Maras', 'Peru', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (452, 'Holiday Inn Express & Suites Columbus - Polaris Parkway', 'Golf View', '1114', 'Lourdes', 'Philippines', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (453, 'Hotel St. Augustine', 'Vermont', '33036 CEDEX', 'Bordeaux', 'France', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (454, 'Holiday Inn Express Albuquerque (I-40 Eubank)', 'Cody', null, 'Cabrero', 'Chile', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (455, 'Days Inn Apple Valley Sevierville', 'Crownhardt', null, 'Chengdong', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (456, 'Holiday Inn Express Suites Denver Sw-Littleton', 'Straubel', '6360', 'Río Cuarto', 'Argentina', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (457, 'Hampton Inn and Suites Baltimore Inner Harbor', 'Blaine', '186 96', 'Vallentuna', 'Sweden', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (458, 'Holiday Inn Express Washington Dc Sw - Springfield', 'Haas', null, 'Sidi Moussa', 'Morocco', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (459, 'Simmons Suites', 'Main', null, 'Huangqiang', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (460, 'Fremont Hotel & Casino', '2nd', null, 'Liji', 'China', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (461, 'Campus Inn Motel', 'Springs', null, 'Yara', 'Cuba', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (462, 'Holiday Inn Express Suites Northwood', 'Harbort', null, 'Weibin', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (463, 'Pacific Inn', 'Clove', null, 'Huzhen', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (464, 'Fairfield Inn Corbin', 'Prentice', '187052', 'Lyuban’', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (465, 'Red Roof Inn Detroit - Southfield', 'Mallory', '2800', 'Bangued', 'Philippines', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (466, 'Best Western Plus Wilmington/Carolina Beach', 'Green', null, 'Nanshui', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (467, 'Hampton Inn & Suites Chapel Hill/Durham', 'Ryan', null, 'Curahkalak Tengah', 'Indonesia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (468, 'Hotel Sutter', 'Straubel', null, 'Fort Dauphin', 'Madagascar', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (469, 'Holiday Inn Express and Suites', 'Hooker', null, 'Dushanbe', 'Tajikistan', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (470, 'Days Inn St. Louis - Lindbergh Boulevard', 'Morningstar', '607320', 'Diveyevo', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (471, 'Seven Gables Inn', 'Kinsman', null, 'Jiamiao', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (472, 'Hotel Lincoln', 'Loomis', null, 'Mardakyany', 'Azerbaijan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (473, 'Microtel Inn Suites by Wyndham Marietta', 'Lunder', null, 'Kribi', 'Cameroon', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (474, 'Drury Inn Suites St. Louis Convention Center', 'Kingsford', null, 'Longquan', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (475, 'Hampton Inn Suites PortlandVancouver', 'Johnson', null, 'Dongshentou', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (476, 'Motel 6 Jaiden & Jiya LLC', 'Shasta', null, 'Yangtan', 'China', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (477, 'Ramada Louisville Expo Center', 'Eagle Crest', null, 'Fort Liberté', 'Haiti', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (478, 'Drury Inn Suites St. Louis Convention Center', 'Meadow Valley', null, 'Fuhai', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (479, 'Econolodge', 'Surrey', '4500', 'Barayong', 'Philippines', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (480, 'Homewood Suites by Hilton Baltimore', 'Hollow Ridge', null, 'Tegalgede Kulon', 'Indonesia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (481, 'Hilton Garden Inn Edison/Raritan Center', 'Bultman', '671712', 'Vilyuchinsk', 'Russia', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (482, 'Baymont Inn Suites Grand Rapids SW/Byron Center', 'Shoshone', '606525', 'Zavolzh’ye', 'Russia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (483, 'Halcyon Hotel', 'Di Loreto', null, 'Molina', 'Chile', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (484, 'Motel Del Rogue', 'Shelley', '30648', 'Ipoh', 'Malaysia', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (485, 'Americas Best Value Inn-corpus Christi North/airport', 'Kinsman', '8420', 'Bukal', 'Philippines', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (486, 'Aloft Jacksonville Tapestry Park', 'Waubesa', null, 'Shahrak', 'Afghanistan', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (487, 'Grand Inn', 'Susan', null, 'Chahe', 'China', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (488, 'Room Mate Lord Balfour', 'Farragut', null, 'Yushikalasu', 'China', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (489, 'Fairfield Inn Philadelphia Airport', 'Mcguire', '460056', 'Khudoyelanskoye', 'Russia', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (490, 'Holiday Inn Express Clermont', 'West', '368209', 'Nizhniy Dzhengutay', 'Russia', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (491, 'Wildflower Inn', 'Mesta', '59320', 'Lodhrān', 'Pakistan', 4);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (492, 'La Cuesta Inn', 'Ryan', '353798', 'Grivenskaya', 'Russia', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (493, 'Holiday Inn Express Suites Northwood', 'Dawn', null, 'U Minh', 'Vietnam', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (494, 'The Bertram Inn & Conference Center', 'Ryan', null, 'Qagan Obo', 'China', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (495, 'Radisson Hotel Valley Forge', 'Fisk', '74000', 'Samut Sakhon', 'Thailand', 1);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (496, 'TownePlace Suites Anaheim Maingate Near Angel Stadium', 'Center', null, 'Maroúsi', 'Greece', 3);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (497, 'Mark Twain Hotel', 'Fairfield', '40524', 'Lexington', 'United States', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (498, 'The Resort at Longboat Key Club', 'Quincy', '20160', 'Phan Thong', 'Thailand', 2);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (499, 'La Quinta Inn & Suites Phoenix I-10 West', 'Towne', '696 35', 'Dambořice', 'Czech Republic', 5);
insert into Hotel (hotelId, name, street, zipcode, city, country, rating) values (500, 'The Boxer', 'Manufacturers', null, 'Riti', 'Nigeria', 5);