ALTER TABLE RESERVATION
ADD roomId INT;

ALTER TABLE RESERVATION
ADD FOREIGN KEY(roomId) REFERENCES ROOM(roomId);

ALTER TABLE RESERVATION
ADD RESERVATION_CHARGE INT;

UPDATE RESERVATION RS SET RS.RESERVATION_CHARGE = CEIL((RS.DATE_OF_DEPARTURE - RS.DATE_OF_ARRIVAL) * (SELECT RT.COST_PER_DAY * (1-RT.DISCOUNT/100)
FROM ROOM_TYPE RT, ROOM RM WHERE RT.ROOMTYPEID = RM.ROOMTYPEID AND RM.ROOMID = RS.ROOMID));

ALTER TABLE RESERVATION
ADD RATING INT;