CREATE TABLE ROOM_TYPE
(
	ROOMTYPEID INT,
	ROOMTYPE_NAME VARCHAR(20),
	BED_TYPE VARCHAR(20),
	COST_PER_DAY INT,
	DISCOUNT INT,
	HOTELID INT,
	PRIMARY KEY(ROOMTYPEID),
	FOREIGN KEY(HOTELID) REFERENCES HOTEL(HOTELID)

);