create table Room_facility (
                               roomID INT,
                               facilities VARCHAR(12)
);
insert into Room_facility (roomID, facilities) values (49, 'Balcony');
insert into Room_facility (roomID, facilities) values (258, 'Television');
insert into Room_facility (roomID, facilities) values (342, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (261, 'Television');
insert into Room_facility (roomID, facilities) values (78, 'Balcony');
insert into Room_facility (roomID, facilities) values (237, 'Television');
insert into Room_facility (roomID, facilities) values (71, 'Balcony');
insert into Room_facility (roomID, facilities) values (239, 'Television');
insert into Room_facility (roomID, facilities) values (358, 'Television');
insert into Room_facility (roomID, facilities) values (169, 'Sea View');
insert into Room_facility (roomID, facilities) values (3, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (127, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (243, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (262, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (292, 'Sea View');
insert into Room_facility (roomID, facilities) values (14, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (110, 'Balcony');
insert into Room_facility (roomID, facilities) values (303, 'Sea View');
insert into Room_facility (roomID, facilities) values (29, 'Television');
insert into Room_facility (roomID, facilities) values (64, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (302, 'Sea View');
insert into Room_facility (roomID, facilities) values (20, 'Television');
insert into Room_facility (roomID, facilities) values (236, 'Television');
insert into Room_facility (roomID, facilities) values (69, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (266, 'Balcony');
insert into Room_facility (roomID, facilities) values (3, 'Sea View');
insert into Room_facility (roomID, facilities) values (400, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (133, 'Balcony');
insert into Room_facility (roomID, facilities) values (394, 'Sea View');
insert into Room_facility (roomID, facilities) values (234, 'Sea View');
insert into Room_facility (roomID, facilities) values (382, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (59, 'Balcony');
insert into Room_facility (roomID, facilities) values (209, 'Balcony');
insert into Room_facility (roomID, facilities) values (234, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (286, 'Balcony');
insert into Room_facility (roomID, facilities) values (102, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (176, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (382, 'Sea View');
insert into Room_facility (roomID, facilities) values (382, 'Sea View');
insert into Room_facility (roomID, facilities) values (204, 'Balcony');
insert into Room_facility (roomID, facilities) values (382, 'Television');
insert into Room_facility (roomID, facilities) values (222, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (76, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (172, 'Sea View');
insert into Room_facility (roomID, facilities) values (273, 'Sea View');
insert into Room_facility (roomID, facilities) values (38, 'Balcony');
insert into Room_facility (roomID, facilities) values (123, 'Sea View');
insert into Room_facility (roomID, facilities) values (200, 'Sea View');
insert into Room_facility (roomID, facilities) values (275, 'Balcony');
insert into Room_facility (roomID, facilities) values (203, 'Balcony');
insert into Room_facility (roomID, facilities) values (329, 'Television');
insert into Room_facility (roomID, facilities) values (73, 'Sea View');
insert into Room_facility (roomID, facilities) values (173, 'Television');
insert into Room_facility (roomID, facilities) values (203, 'Television');
insert into Room_facility (roomID, facilities) values (154, 'Sea View');
insert into Room_facility (roomID, facilities) values (137, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (63, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (395, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (259, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (73, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (48, 'Sea View');
insert into Room_facility (roomID, facilities) values (15, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (237, 'Balcony');
insert into Room_facility (roomID, facilities) values (332, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (327, 'Television');
insert into Room_facility (roomID, facilities) values (121, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (234, 'Television');
insert into Room_facility (roomID, facilities) values (37, 'Sea View');
insert into Room_facility (roomID, facilities) values (47, 'Sea View');
insert into Room_facility (roomID, facilities) values (296, 'Television');
insert into Room_facility (roomID, facilities) values (360, 'Balcony');
insert into Room_facility (roomID, facilities) values (255, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (211, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (7, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (208, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (311, 'Balcony');
insert into Room_facility (roomID, facilities) values (376, 'Balcony');
insert into Room_facility (roomID, facilities) values (50, 'Balcony');
insert into Room_facility (roomID, facilities) values (237, 'Television');
insert into Room_facility (roomID, facilities) values (55, 'Balcony');
insert into Room_facility (roomID, facilities) values (372, 'Television');
insert into Room_facility (roomID, facilities) values (241, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (236, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (291, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (339, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (19, 'Sea View');
insert into Room_facility (roomID, facilities) values (97, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (40, 'Sea View');
insert into Room_facility (roomID, facilities) values (303, 'Television');
insert into Room_facility (roomID, facilities) values (179, 'Television');
insert into Room_facility (roomID, facilities) values (170, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (275, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (227, 'Sea View');
insert into Room_facility (roomID, facilities) values (137, 'Balcony');
insert into Room_facility (roomID, facilities) values (297, 'Sea View');
insert into Room_facility (roomID, facilities) values (271, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (171, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (294, 'Television');
insert into Room_facility (roomID, facilities) values (300, 'Television');
insert into Room_facility (roomID, facilities) values (328, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (386, 'Balcony');
insert into Room_facility (roomID, facilities) values (142, 'Television');
insert into Room_facility (roomID, facilities) values (215, 'Sea View');
insert into Room_facility (roomID, facilities) values (333, 'Balcony');
insert into Room_facility (roomID, facilities) values (173, 'Television');
insert into Room_facility (roomID, facilities) values (308, 'Balcony');
insert into Room_facility (roomID, facilities) values (181, 'Balcony');
insert into Room_facility (roomID, facilities) values (370, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (170, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (88, 'Sea View');
insert into Room_facility (roomID, facilities) values (90, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (35, 'Balcony');
insert into Room_facility (roomID, facilities) values (114, 'Television');
insert into Room_facility (roomID, facilities) values (112, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (332, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (259, 'Television');
insert into Room_facility (roomID, facilities) values (60, 'Television');
insert into Room_facility (roomID, facilities) values (21, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (143, 'Balcony');
insert into Room_facility (roomID, facilities) values (266, 'Television');
insert into Room_facility (roomID, facilities) values (140, 'Sea View');
insert into Room_facility (roomID, facilities) values (382, 'Television');
insert into Room_facility (roomID, facilities) values (109, 'Television');
insert into Room_facility (roomID, facilities) values (49, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (299, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (180, 'Sea View');
insert into Room_facility (roomID, facilities) values (58, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (63, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (48, 'Sea View');
insert into Room_facility (roomID, facilities) values (372, 'Television');
insert into Room_facility (roomID, facilities) values (224, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (282, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (83, 'Sea View');
insert into Room_facility (roomID, facilities) values (265, 'Television');
insert into Room_facility (roomID, facilities) values (190, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (38, 'Balcony');
insert into Room_facility (roomID, facilities) values (278, 'Sea View');
insert into Room_facility (roomID, facilities) values (53, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (168, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (360, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (315, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (194, 'Television');
insert into Room_facility (roomID, facilities) values (15, 'Balcony');
insert into Room_facility (roomID, facilities) values (94, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (74, 'Balcony');
insert into Room_facility (roomID, facilities) values (26, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (308, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (29, 'Sea View');
insert into Room_facility (roomID, facilities) values (294, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (307, 'Balcony');
insert into Room_facility (roomID, facilities) values (29, 'Balcony');
insert into Room_facility (roomID, facilities) values (327, 'Balcony');
insert into Room_facility (roomID, facilities) values (182, 'Television');
insert into Room_facility (roomID, facilities) values (200, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (124, 'Balcony');
insert into Room_facility (roomID, facilities) values (292, 'Television');
insert into Room_facility (roomID, facilities) values (391, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (3, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (377, 'Television');
insert into Room_facility (roomID, facilities) values (150, 'Television');
insert into Room_facility (roomID, facilities) values (151, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (285, 'Balcony');
insert into Room_facility (roomID, facilities) values (190, 'Television');
insert into Room_facility (roomID, facilities) values (101, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (220, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (64, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (383, 'Television');
insert into Room_facility (roomID, facilities) values (298, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (378, 'Balcony');
insert into Room_facility (roomID, facilities) values (123, 'Television');
insert into Room_facility (roomID, facilities) values (353, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (148, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (162, 'Balcony');
insert into Room_facility (roomID, facilities) values (4, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (210, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (302, 'Television');
insert into Room_facility (roomID, facilities) values (344, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (300, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (370, 'Sea View');
insert into Room_facility (roomID, facilities) values (115, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (340, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (377, 'Television');
insert into Room_facility (roomID, facilities) values (35, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (13, 'Balcony');
insert into Room_facility (roomID, facilities) values (398, 'Balcony');
insert into Room_facility (roomID, facilities) values (318, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (162, 'Television');
insert into Room_facility (roomID, facilities) values (321, 'Balcony');
insert into Room_facility (roomID, facilities) values (305, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (249, 'Balcony');
insert into Room_facility (roomID, facilities) values (364, 'Television');
insert into Room_facility (roomID, facilities) values (25, 'Balcony');
insert into Room_facility (roomID, facilities) values (181, 'Television');
insert into Room_facility (roomID, facilities) values (15, 'Balcony');
insert into Room_facility (roomID, facilities) values (241, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (99, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (237, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (89, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (29, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (257, 'Sea View');
insert into Room_facility (roomID, facilities) values (157, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (266, 'Sea View');
insert into Room_facility (roomID, facilities) values (13, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (30, 'Balcony');
insert into Room_facility (roomID, facilities) values (323, 'Balcony');
insert into Room_facility (roomID, facilities) values (20, 'Balcony');
insert into Room_facility (roomID, facilities) values (389, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (192, 'Television');
insert into Room_facility (roomID, facilities) values (315, 'Television');
insert into Room_facility (roomID, facilities) values (130, 'Sea View');
insert into Room_facility (roomID, facilities) values (88, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (101, 'Sea View');
insert into Room_facility (roomID, facilities) values (251, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (346, 'Sea View');
insert into Room_facility (roomID, facilities) values (29, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (326, 'Balcony');
insert into Room_facility (roomID, facilities) values (29, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (189, 'Sea View');
insert into Room_facility (roomID, facilities) values (214, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (50, 'Balcony');
insert into Room_facility (roomID, facilities) values (183, 'Sea View');
insert into Room_facility (roomID, facilities) values (391, 'Television');
insert into Room_facility (roomID, facilities) values (329, 'Balcony');
insert into Room_facility (roomID, facilities) values (134, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (41, 'Balcony');
insert into Room_facility (roomID, facilities) values (225, 'Balcony');
insert into Room_facility (roomID, facilities) values (278, 'Balcony');
insert into Room_facility (roomID, facilities) values (6, 'Sea View');
insert into Room_facility (roomID, facilities) values (291, 'Television');
insert into Room_facility (roomID, facilities) values (319, 'Television');
insert into Room_facility (roomID, facilities) values (122, 'Television');
insert into Room_facility (roomID, facilities) values (11, 'Sea View');
insert into Room_facility (roomID, facilities) values (122, 'Television');
insert into Room_facility (roomID, facilities) values (337, 'Sea View');
insert into Room_facility (roomID, facilities) values (94, 'Balcony');
insert into Room_facility (roomID, facilities) values (17, 'Television');
insert into Room_facility (roomID, facilities) values (176, 'Balcony');
insert into Room_facility (roomID, facilities) values (274, 'Television');
insert into Room_facility (roomID, facilities) values (269, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (106, 'Sea View');
insert into Room_facility (roomID, facilities) values (288, 'Sea View');
insert into Room_facility (roomID, facilities) values (84, 'Television');
insert into Room_facility (roomID, facilities) values (168, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (303, 'Television');
insert into Room_facility (roomID, facilities) values (10, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (350, 'Sea View');
insert into Room_facility (roomID, facilities) values (371, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (274, 'Television');
insert into Room_facility (roomID, facilities) values (29, 'Balcony');
insert into Room_facility (roomID, facilities) values (323, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (28, 'Balcony');
insert into Room_facility (roomID, facilities) values (313, 'Sea View');
insert into Room_facility (roomID, facilities) values (224, 'Sea View');
insert into Room_facility (roomID, facilities) values (23, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (4, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (184, 'Sea View');
insert into Room_facility (roomID, facilities) values (141, 'Television');
insert into Room_facility (roomID, facilities) values (396, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (383, 'Balcony');
insert into Room_facility (roomID, facilities) values (29, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (36, 'Television');
insert into Room_facility (roomID, facilities) values (80, 'Television');
insert into Room_facility (roomID, facilities) values (113, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (329, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (298, 'Sea View');
insert into Room_facility (roomID, facilities) values (102, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (2, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (37, 'Sea View');
insert into Room_facility (roomID, facilities) values (213, 'Television');
insert into Room_facility (roomID, facilities) values (104, 'Balcony');
insert into Room_facility (roomID, facilities) values (116, 'Television');
insert into Room_facility (roomID, facilities) values (305, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (312, 'Television');
insert into Room_facility (roomID, facilities) values (156, 'Balcony');
insert into Room_facility (roomID, facilities) values (116, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (349, 'Sea View');
insert into Room_facility (roomID, facilities) values (339, 'Balcony');
insert into Room_facility (roomID, facilities) values (66, 'Balcony');
insert into Room_facility (roomID, facilities) values (349, 'Balcony');
insert into Room_facility (roomID, facilities) values (4, 'Sea View');
insert into Room_facility (roomID, facilities) values (245, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (302, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (165, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (376, 'Television');
insert into Room_facility (roomID, facilities) values (21, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (99, 'Television');
insert into Room_facility (roomID, facilities) values (386, 'Sea View');
insert into Room_facility (roomID, facilities) values (231, 'Balcony');
insert into Room_facility (roomID, facilities) values (70, 'Sea View');
insert into Room_facility (roomID, facilities) values (188, 'Television');
insert into Room_facility (roomID, facilities) values (284, 'Sea View');
insert into Room_facility (roomID, facilities) values (359, 'Balcony');
insert into Room_facility (roomID, facilities) values (336, 'Television');
insert into Room_facility (roomID, facilities) values (92, 'Balcony');
insert into Room_facility (roomID, facilities) values (131, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (324, 'Television');
insert into Room_facility (roomID, facilities) values (22, 'Balcony');
insert into Room_facility (roomID, facilities) values (117, 'Balcony');
insert into Room_facility (roomID, facilities) values (175, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (113, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (309, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (209, 'Balcony');
insert into Room_facility (roomID, facilities) values (129, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (269, 'Sea View');
insert into Room_facility (roomID, facilities) values (281, 'Television');
insert into Room_facility (roomID, facilities) values (248, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (189, 'Sea View');
insert into Room_facility (roomID, facilities) values (13, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (309, 'Sea View');
insert into Room_facility (roomID, facilities) values (54, 'Balcony');
insert into Room_facility (roomID, facilities) values (134, 'Sea View');
insert into Room_facility (roomID, facilities) values (176, 'Balcony');
insert into Room_facility (roomID, facilities) values (242, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (86, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (116, 'Sea View');
insert into Room_facility (roomID, facilities) values (312, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (5, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (133, 'Sea View');
insert into Room_facility (roomID, facilities) values (314, 'Sea View');
insert into Room_facility (roomID, facilities) values (114, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (363, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (55, 'Balcony');
insert into Room_facility (roomID, facilities) values (207, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (228, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (280, 'Balcony');
insert into Room_facility (roomID, facilities) values (241, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (102, 'Television');
insert into Room_facility (roomID, facilities) values (188, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (293, 'Sea View');
insert into Room_facility (roomID, facilities) values (330, 'Sea View');
insert into Room_facility (roomID, facilities) values (222, 'Balcony');
insert into Room_facility (roomID, facilities) values (335, 'Sea View');
insert into Room_facility (roomID, facilities) values (298, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (154, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (292, 'Sea View');
insert into Room_facility (roomID, facilities) values (13, 'Balcony');
insert into Room_facility (roomID, facilities) values (337, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (367, 'Sea View');
insert into Room_facility (roomID, facilities) values (352, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (329, 'Balcony');
insert into Room_facility (roomID, facilities) values (3, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (131, 'Balcony');
insert into Room_facility (roomID, facilities) values (1, 'Sea View');
insert into Room_facility (roomID, facilities) values (152, 'Television');
insert into Room_facility (roomID, facilities) values (292, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (280, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (254, 'Balcony');
insert into Room_facility (roomID, facilities) values (93, 'Balcony');
insert into Room_facility (roomID, facilities) values (42, 'Balcony');
insert into Room_facility (roomID, facilities) values (123, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (19, 'Television');
insert into Room_facility (roomID, facilities) values (8, 'Balcony');
insert into Room_facility (roomID, facilities) values (209, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (133, 'Television');
insert into Room_facility (roomID, facilities) values (264, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (201, 'Sea View');
insert into Room_facility (roomID, facilities) values (168, 'Sea View');
insert into Room_facility (roomID, facilities) values (53, 'Television');
insert into Room_facility (roomID, facilities) values (56, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (264, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (65, 'Sea View');
insert into Room_facility (roomID, facilities) values (217, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (145, 'Television');
insert into Room_facility (roomID, facilities) values (304, 'Sea View');
insert into Room_facility (roomID, facilities) values (310, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (56, 'Balcony');
insert into Room_facility (roomID, facilities) values (33, 'Sea View');
insert into Room_facility (roomID, facilities) values (154, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (16, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (62, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (61, 'Sea View');
insert into Room_facility (roomID, facilities) values (365, 'Sea View');
insert into Room_facility (roomID, facilities) values (212, 'Television');
insert into Room_facility (roomID, facilities) values (235, 'Sea View');
insert into Room_facility (roomID, facilities) values (63, 'Television');
insert into Room_facility (roomID, facilities) values (182, 'Balcony');
insert into Room_facility (roomID, facilities) values (147, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (309, 'Television');
insert into Room_facility (roomID, facilities) values (297, 'Television');
insert into Room_facility (roomID, facilities) values (119, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (279, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (126, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (33, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (263, 'Television');
insert into Room_facility (roomID, facilities) values (342, 'Balcony');
insert into Room_facility (roomID, facilities) values (299, 'Sea View');
insert into Room_facility (roomID, facilities) values (264, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (108, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (336, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (292, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (3, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (372, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (164, 'Balcony');
insert into Room_facility (roomID, facilities) values (384, 'Sea View');
insert into Room_facility (roomID, facilities) values (94, 'Television');
insert into Room_facility (roomID, facilities) values (235, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (58, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (353, 'Balcony');
insert into Room_facility (roomID, facilities) values (210, 'Balcony');
insert into Room_facility (roomID, facilities) values (86, 'Sea View');
insert into Room_facility (roomID, facilities) values (109, 'Television');
insert into Room_facility (roomID, facilities) values (12, 'Television');
insert into Room_facility (roomID, facilities) values (6, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (298, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (164, 'Sea View');
insert into Room_facility (roomID, facilities) values (284, 'Sea View');
insert into Room_facility (roomID, facilities) values (102, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (7, 'Sea View');
insert into Room_facility (roomID, facilities) values (234, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (164, 'Sea View');
insert into Room_facility (roomID, facilities) values (380, 'Balcony');
insert into Room_facility (roomID, facilities) values (136, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (184, 'Television');
insert into Room_facility (roomID, facilities) values (176, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (193, 'Sea View');
insert into Room_facility (roomID, facilities) values (141, 'Balcony');
insert into Room_facility (roomID, facilities) values (159, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (335, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (261, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (8, 'Sea View');
insert into Room_facility (roomID, facilities) values (64, 'Television');
insert into Room_facility (roomID, facilities) values (15, 'Television');
insert into Room_facility (roomID, facilities) values (207, 'Television');
insert into Room_facility (roomID, facilities) values (335, 'Television');
insert into Room_facility (roomID, facilities) values (327, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (199, 'Balcony');
insert into Room_facility (roomID, facilities) values (56, 'Television');
insert into Room_facility (roomID, facilities) values (321, 'Television');
insert into Room_facility (roomID, facilities) values (188, 'Sea View');
insert into Room_facility (roomID, facilities) values (163, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (309, 'Balcony');
insert into Room_facility (roomID, facilities) values (328, 'Balcony');
insert into Room_facility (roomID, facilities) values (299, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (173, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (385, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (302, 'Sea View');
insert into Room_facility (roomID, facilities) values (333, 'Sea View');
insert into Room_facility (roomID, facilities) values (267, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (30, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (114, 'Television');
insert into Room_facility (roomID, facilities) values (278, 'Balcony');
insert into Room_facility (roomID, facilities) values (142, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (6, 'Sea View');
insert into Room_facility (roomID, facilities) values (320, 'Sea View');
insert into Room_facility (roomID, facilities) values (302, 'Sea View');
insert into Room_facility (roomID, facilities) values (296, 'Sea View');
insert into Room_facility (roomID, facilities) values (395, 'Balcony');
insert into Room_facility (roomID, facilities) values (218, 'Television');
insert into Room_facility (roomID, facilities) values (256, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (368, 'Television');
insert into Room_facility (roomID, facilities) values (114, 'Sea View');
insert into Room_facility (roomID, facilities) values (135, 'Sea View');
insert into Room_facility (roomID, facilities) values (252, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (283, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (266, 'Television');
insert into Room_facility (roomID, facilities) values (268, 'Sea View');
insert into Room_facility (roomID, facilities) values (286, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (382, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (369, 'Sea View');
insert into Room_facility (roomID, facilities) values (220, 'Television');
insert into Room_facility (roomID, facilities) values (385, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (351, 'Sea View');
insert into Room_facility (roomID, facilities) values (363, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (346, 'Sea View');
insert into Room_facility (roomID, facilities) values (29, 'Balcony');
insert into Room_facility (roomID, facilities) values (368, 'Television');
insert into Room_facility (roomID, facilities) values (192, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (367, 'Sea View');
insert into Room_facility (roomID, facilities) values (294, 'Balcony');
insert into Room_facility (roomID, facilities) values (385, 'Sea View');
insert into Room_facility (roomID, facilities) values (369, 'Television');
insert into Room_facility (roomID, facilities) values (96, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (172, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (315, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (36, 'Balcony');
insert into Room_facility (roomID, facilities) values (124, 'Sea View');
insert into Room_facility (roomID, facilities) values (153, 'Television');
insert into Room_facility (roomID, facilities) values (65, 'Television');
insert into Room_facility (roomID, facilities) values (40, 'Balcony');
insert into Room_facility (roomID, facilities) values (164, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (289, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (57, 'Balcony');
insert into Room_facility (roomID, facilities) values (252, 'Television');
insert into Room_facility (roomID, facilities) values (141, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (168, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (142, 'Television');
insert into Room_facility (roomID, facilities) values (105, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (282, 'Balcony');
insert into Room_facility (roomID, facilities) values (164, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (330, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (184, 'Television');
insert into Room_facility (roomID, facilities) values (305, 'Balcony');
insert into Room_facility (roomID, facilities) values (309, 'Balcony');
insert into Room_facility (roomID, facilities) values (382, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (1, 'Balcony');
insert into Room_facility (roomID, facilities) values (205, 'Television');
insert into Room_facility (roomID, facilities) values (139, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (145, 'Balcony');
insert into Room_facility (roomID, facilities) values (236, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (169, 'Television');
insert into Room_facility (roomID, facilities) values (291, 'Balcony');
insert into Room_facility (roomID, facilities) values (363, 'Balcony');
insert into Room_facility (roomID, facilities) values (266, 'Sea View');
insert into Room_facility (roomID, facilities) values (229, 'Television');
insert into Room_facility (roomID, facilities) values (168, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (249, 'Sea View');
insert into Room_facility (roomID, facilities) values (311, 'Balcony');
insert into Room_facility (roomID, facilities) values (297, 'Television');
insert into Room_facility (roomID, facilities) values (71, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (169, 'Television');
insert into Room_facility (roomID, facilities) values (80, 'Sea View');
insert into Room_facility (roomID, facilities) values (160, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (76, 'Television');
insert into Room_facility (roomID, facilities) values (390, 'Balcony');
insert into Room_facility (roomID, facilities) values (130, 'Sea View');
insert into Room_facility (roomID, facilities) values (44, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (305, 'Balcony');
insert into Room_facility (roomID, facilities) values (331, 'Television');
insert into Room_facility (roomID, facilities) values (90, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (141, 'Balcony');
insert into Room_facility (roomID, facilities) values (123, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (139, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (322, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (284, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (360, 'Television');
insert into Room_facility (roomID, facilities) values (272, 'Balcony');
insert into Room_facility (roomID, facilities) values (176, 'Television');
insert into Room_facility (roomID, facilities) values (331, 'Balcony');
insert into Room_facility (roomID, facilities) values (323, 'Television');
insert into Room_facility (roomID, facilities) values (5, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (339, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (74, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (298, 'Sea View');
insert into Room_facility (roomID, facilities) values (396, 'Balcony');
insert into Room_facility (roomID, facilities) values (277, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (373, 'Balcony');
insert into Room_facility (roomID, facilities) values (265, 'Television');
insert into Room_facility (roomID, facilities) values (1, 'Television');
insert into Room_facility (roomID, facilities) values (356, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (72, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (87, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (386, 'Television');
insert into Room_facility (roomID, facilities) values (347, 'Television');
insert into Room_facility (roomID, facilities) values (211, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (395, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (84, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (357, 'Sea View');
insert into Room_facility (roomID, facilities) values (337, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (285, 'Sea View');
insert into Room_facility (roomID, facilities) values (271, 'Sea View');
insert into Room_facility (roomID, facilities) values (109, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (277, 'Balcony');
insert into Room_facility (roomID, facilities) values (70, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (146, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (364, 'Sea View');
insert into Room_facility (roomID, facilities) values (364, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (227, 'Sea View');
insert into Room_facility (roomID, facilities) values (125, 'Sea View');
insert into Room_facility (roomID, facilities) values (1, 'Television');
insert into Room_facility (roomID, facilities) values (298, 'Sea View');
insert into Room_facility (roomID, facilities) values (52, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (364, 'Television');
insert into Room_facility (roomID, facilities) values (75, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (334, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (233, 'Balcony');
insert into Room_facility (roomID, facilities) values (390, 'Sea View');
insert into Room_facility (roomID, facilities) values (185, 'Television');
insert into Room_facility (roomID, facilities) values (195, 'Sea View');
insert into Room_facility (roomID, facilities) values (143, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (233, 'Sea View');
insert into Room_facility (roomID, facilities) values (284, 'Sea View');
insert into Room_facility (roomID, facilities) values (274, 'Sea View');
insert into Room_facility (roomID, facilities) values (9, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (236, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (372, 'Sea View');
insert into Room_facility (roomID, facilities) values (298, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (292, 'Balcony');
insert into Room_facility (roomID, facilities) values (128, 'Sea View');
insert into Room_facility (roomID, facilities) values (257, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (116, 'Balcony');
insert into Room_facility (roomID, facilities) values (295, 'Television');
insert into Room_facility (roomID, facilities) values (66, 'Balcony');
insert into Room_facility (roomID, facilities) values (119, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (71, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (180, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (336, 'Sea View');
insert into Room_facility (roomID, facilities) values (119, 'Sea View');
insert into Room_facility (roomID, facilities) values (388, 'Balcony');
insert into Room_facility (roomID, facilities) values (168, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (351, 'Television');
insert into Room_facility (roomID, facilities) values (90, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (252, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (276, 'Television');
insert into Room_facility (roomID, facilities) values (299, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (285, 'Television');
insert into Room_facility (roomID, facilities) values (153, 'Sea View');
insert into Room_facility (roomID, facilities) values (99, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (113, 'Balcony');
insert into Room_facility (roomID, facilities) values (169, 'Balcony');
insert into Room_facility (roomID, facilities) values (309, 'Balcony');
insert into Room_facility (roomID, facilities) values (298, 'Balcony');
insert into Room_facility (roomID, facilities) values (60, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (167, 'Television');
insert into Room_facility (roomID, facilities) values (271, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (258, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (51, 'Television');
insert into Room_facility (roomID, facilities) values (248, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (17, 'Sea View');
insert into Room_facility (roomID, facilities) values (264, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (211, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (104, 'Balcony');
insert into Room_facility (roomID, facilities) values (10, 'Sea View');
insert into Room_facility (roomID, facilities) values (22, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (321, 'Television');
insert into Room_facility (roomID, facilities) values (391, 'Sea View');
insert into Room_facility (roomID, facilities) values (50, 'Television');
insert into Room_facility (roomID, facilities) values (229, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (263, 'Balcony');
insert into Room_facility (roomID, facilities) values (165, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (319, 'Sea View');
insert into Room_facility (roomID, facilities) values (12, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (49, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (67, 'Balcony');
insert into Room_facility (roomID, facilities) values (144, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (67, 'Balcony');
insert into Room_facility (roomID, facilities) values (390, 'Television');
insert into Room_facility (roomID, facilities) values (121, 'Balcony');
insert into Room_facility (roomID, facilities) values (105, 'Balcony');
insert into Room_facility (roomID, facilities) values (323, 'Television');
insert into Room_facility (roomID, facilities) values (333, 'Balcony');
insert into Room_facility (roomID, facilities) values (160, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (27, 'Sea View');
insert into Room_facility (roomID, facilities) values (20, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (214, 'Sea View');
insert into Room_facility (roomID, facilities) values (191, 'Balcony');
insert into Room_facility (roomID, facilities) values (83, 'Balcony');
insert into Room_facility (roomID, facilities) values (95, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (38, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (301, 'Sea View');
insert into Room_facility (roomID, facilities) values (315, 'Sea View');
insert into Room_facility (roomID, facilities) values (159, 'Television');
insert into Room_facility (roomID, facilities) values (377, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (64, 'Television');
insert into Room_facility (roomID, facilities) values (134, 'Television');
insert into Room_facility (roomID, facilities) values (240, 'Television');
insert into Room_facility (roomID, facilities) values (332, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (400, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (241, 'Balcony');
insert into Room_facility (roomID, facilities) values (206, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (15, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (135, 'Television');
insert into Room_facility (roomID, facilities) values (352, 'Sea View');
insert into Room_facility (roomID, facilities) values (111, 'Sea View');
insert into Room_facility (roomID, facilities) values (336, 'Sea View');
insert into Room_facility (roomID, facilities) values (381, 'Television');
insert into Room_facility (roomID, facilities) values (128, 'Balcony');
insert into Room_facility (roomID, facilities) values (212, 'Balcony');
insert into Room_facility (roomID, facilities) values (50, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (258, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (249, 'Television');
insert into Room_facility (roomID, facilities) values (304, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (319, 'Television');
insert into Room_facility (roomID, facilities) values (132, 'Sea View');
insert into Room_facility (roomID, facilities) values (336, 'Television');
insert into Room_facility (roomID, facilities) values (382, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (197, 'Television');
insert into Room_facility (roomID, facilities) values (67, 'Sea View');
insert into Room_facility (roomID, facilities) values (390, 'Sea View');
insert into Room_facility (roomID, facilities) values (17, 'Sea View');
insert into Room_facility (roomID, facilities) values (391, 'Balcony');
insert into Room_facility (roomID, facilities) values (301, 'Balcony');
insert into Room_facility (roomID, facilities) values (126, 'Television');
insert into Room_facility (roomID, facilities) values (363, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (200, 'Balcony');
insert into Room_facility (roomID, facilities) values (165, 'Sea View');
insert into Room_facility (roomID, facilities) values (45, 'Sea View');
insert into Room_facility (roomID, facilities) values (334, 'Sea View');
insert into Room_facility (roomID, facilities) values (142, 'Balcony');
insert into Room_facility (roomID, facilities) values (19, 'Balcony');
insert into Room_facility (roomID, facilities) values (308, 'Television');
insert into Room_facility (roomID, facilities) values (154, 'Sea View');
insert into Room_facility (roomID, facilities) values (374, 'Television');
insert into Room_facility (roomID, facilities) values (184, 'Television');
insert into Room_facility (roomID, facilities) values (289, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (27, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (97, 'Sea View');
insert into Room_facility (roomID, facilities) values (238, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (112, 'Television');
insert into Room_facility (roomID, facilities) values (322, 'Sea View');
insert into Room_facility (roomID, facilities) values (262, 'Sea View');
insert into Room_facility (roomID, facilities) values (150, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (241, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (370, 'Television');
insert into Room_facility (roomID, facilities) values (44, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (71, 'Sea View');
insert into Room_facility (roomID, facilities) values (101, 'Television');
insert into Room_facility (roomID, facilities) values (212, 'Sea View');
insert into Room_facility (roomID, facilities) values (305, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (106, 'Sea View');
insert into Room_facility (roomID, facilities) values (36, 'Television');
insert into Room_facility (roomID, facilities) values (351, 'Television');
insert into Room_facility (roomID, facilities) values (152, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (119, 'Sea View');
insert into Room_facility (roomID, facilities) values (50, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (267, 'Sea View');
insert into Room_facility (roomID, facilities) values (207, 'Sea View');
insert into Room_facility (roomID, facilities) values (24, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (335, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (358, 'Sea View');
insert into Room_facility (roomID, facilities) values (316, 'Sea View');
insert into Room_facility (roomID, facilities) values (23, 'Balcony');
insert into Room_facility (roomID, facilities) values (6, 'Balcony');
insert into Room_facility (roomID, facilities) values (193, 'Television');
insert into Room_facility (roomID, facilities) values (317, 'Balcony');
insert into Room_facility (roomID, facilities) values (246, 'Balcony');
insert into Room_facility (roomID, facilities) values (57, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (8, 'Television');
insert into Room_facility (roomID, facilities) values (159, 'Television');
insert into Room_facility (roomID, facilities) values (51, 'Sea View');
insert into Room_facility (roomID, facilities) values (312, 'Sea View');
insert into Room_facility (roomID, facilities) values (189, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (146, 'Television');
insert into Room_facility (roomID, facilities) values (85, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (113, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (379, 'Television');
insert into Room_facility (roomID, facilities) values (240, 'Sea View');
insert into Room_facility (roomID, facilities) values (237, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (252, 'Balcony');
insert into Room_facility (roomID, facilities) values (389, 'Television');
insert into Room_facility (roomID, facilities) values (187, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (34, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (379, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (125, 'Balcony');
insert into Room_facility (roomID, facilities) values (387, 'Sea View');
insert into Room_facility (roomID, facilities) values (83, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (34, 'Television');
insert into Room_facility (roomID, facilities) values (284, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (217, 'Sea View');
insert into Room_facility (roomID, facilities) values (98, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (193, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (49, 'Sea View');
insert into Room_facility (roomID, facilities) values (168, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (269, 'Television');
insert into Room_facility (roomID, facilities) values (11, 'Sea View');
insert into Room_facility (roomID, facilities) values (214, 'Sea View');
insert into Room_facility (roomID, facilities) values (76, 'Television');
insert into Room_facility (roomID, facilities) values (376, 'Sea View');
insert into Room_facility (roomID, facilities) values (209, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (359, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (344, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (376, 'Balcony');
insert into Room_facility (roomID, facilities) values (253, 'Sea View');
insert into Room_facility (roomID, facilities) values (258, 'Television');
insert into Room_facility (roomID, facilities) values (295, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (109, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (57, 'Sea View');
insert into Room_facility (roomID, facilities) values (168, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (197, 'Television');
insert into Room_facility (roomID, facilities) values (191, 'Balcony');
insert into Room_facility (roomID, facilities) values (77, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (90, 'Television');
insert into Room_facility (roomID, facilities) values (20, 'Sea View');
insert into Room_facility (roomID, facilities) values (283, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (251, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (199, 'Television');
insert into Room_facility (roomID, facilities) values (372, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (139, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (148, 'Sea View');
insert into Room_facility (roomID, facilities) values (294, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (378, 'Sea View');
insert into Room_facility (roomID, facilities) values (11, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (390, 'Balcony');
insert into Room_facility (roomID, facilities) values (353, 'Television');
insert into Room_facility (roomID, facilities) values (96, 'Television');
insert into Room_facility (roomID, facilities) values (257, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (372, 'Sea View');
insert into Room_facility (roomID, facilities) values (346, 'Balcony');
insert into Room_facility (roomID, facilities) values (16, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (337, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (56, 'Television');
insert into Room_facility (roomID, facilities) values (388, 'Balcony');
insert into Room_facility (roomID, facilities) values (80, 'Television');
insert into Room_facility (roomID, facilities) values (311, 'Balcony');
insert into Room_facility (roomID, facilities) values (37, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (374, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (176, 'Balcony');
insert into Room_facility (roomID, facilities) values (293, 'Sea View');
insert into Room_facility (roomID, facilities) values (96, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (205, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (208, 'Sea View');
insert into Room_facility (roomID, facilities) values (33, 'Television');
insert into Room_facility (roomID, facilities) values (390, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (263, 'Balcony');
insert into Room_facility (roomID, facilities) values (357, 'Balcony');
insert into Room_facility (roomID, facilities) values (90, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (335, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (183, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (56, 'Balcony');
insert into Room_facility (roomID, facilities) values (171, 'Sea View');
insert into Room_facility (roomID, facilities) values (179, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (161, 'Sea View');
insert into Room_facility (roomID, facilities) values (256, 'Television');
insert into Room_facility (roomID, facilities) values (316, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (72, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (185, 'Television');
insert into Room_facility (roomID, facilities) values (80, 'Balcony');
insert into Room_facility (roomID, facilities) values (176, 'Balcony');
insert into Room_facility (roomID, facilities) values (103, 'Balcony');
insert into Room_facility (roomID, facilities) values (111, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (215, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (225, 'Television');
insert into Room_facility (roomID, facilities) values (391, 'Sea View');
insert into Room_facility (roomID, facilities) values (245, 'Sea View');
insert into Room_facility (roomID, facilities) values (317, 'Television');
insert into Room_facility (roomID, facilities) values (32, 'Television');
insert into Room_facility (roomID, facilities) values (327, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (86, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (107, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (301, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (263, 'Sea View');
insert into Room_facility (roomID, facilities) values (71, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (361, 'Sea View');
insert into Room_facility (roomID, facilities) values (293, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (234, 'Sea View');
insert into Room_facility (roomID, facilities) values (244, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (249, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (244, 'Television');
insert into Room_facility (roomID, facilities) values (281, 'Television');
insert into Room_facility (roomID, facilities) values (114, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (60, 'Sea View');
insert into Room_facility (roomID, facilities) values (93, 'Sea View');
insert into Room_facility (roomID, facilities) values (317, 'Sea View');
insert into Room_facility (roomID, facilities) values (19, 'Sea View');
insert into Room_facility (roomID, facilities) values (206, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (354, 'Balcony');
insert into Room_facility (roomID, facilities) values (216, 'Balcony');
insert into Room_facility (roomID, facilities) values (138, 'Sea View');
insert into Room_facility (roomID, facilities) values (41, 'Sea View');
insert into Room_facility (roomID, facilities) values (29, 'Balcony');
insert into Room_facility (roomID, facilities) values (163, 'Television');
insert into Room_facility (roomID, facilities) values (322, 'Television');
insert into Room_facility (roomID, facilities) values (334, 'Sea View');
insert into Room_facility (roomID, facilities) values (16, 'Television');
insert into Room_facility (roomID, facilities) values (240, 'Balcony');
insert into Room_facility (roomID, facilities) values (71, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (285, 'Balcony');
insert into Room_facility (roomID, facilities) values (324, 'Sea View');
insert into Room_facility (roomID, facilities) values (226, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (230, 'Balcony');
insert into Room_facility (roomID, facilities) values (104, 'Sea View');
insert into Room_facility (roomID, facilities) values (147, 'Television');
insert into Room_facility (roomID, facilities) values (70, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (158, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (70, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (137, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (208, 'Television');
insert into Room_facility (roomID, facilities) values (263, 'Balcony');
insert into Room_facility (roomID, facilities) values (322, 'Television');
insert into Room_facility (roomID, facilities) values (250, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (327, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (49, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (226, 'Balcony');
insert into Room_facility (roomID, facilities) values (303, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (241, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (8, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (394, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (21, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (325, 'Television');
insert into Room_facility (roomID, facilities) values (243, 'Television');
insert into Room_facility (roomID, facilities) values (111, 'Balcony');
insert into Room_facility (roomID, facilities) values (358, 'Balcony');
insert into Room_facility (roomID, facilities) values (285, 'Television');
insert into Room_facility (roomID, facilities) values (209, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (394, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (260, 'Balcony');
insert into Room_facility (roomID, facilities) values (343, 'Sea View');
insert into Room_facility (roomID, facilities) values (280, 'Balcony');
insert into Room_facility (roomID, facilities) values (134, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (215, 'Sea View');
insert into Room_facility (roomID, facilities) values (72, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (333, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (382, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (259, 'Sea View');
insert into Room_facility (roomID, facilities) values (299, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (282, 'Balcony');
insert into Room_facility (roomID, facilities) values (113, 'Balcony');
insert into Room_facility (roomID, facilities) values (242, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (335, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (382, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (307, 'Balcony');
insert into Room_facility (roomID, facilities) values (13, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (6, 'Sea View');
insert into Room_facility (roomID, facilities) values (162, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (264, 'Balcony');
insert into Room_facility (roomID, facilities) values (394, 'Balcony');
insert into Room_facility (roomID, facilities) values (25, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (44, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (156, 'Television');
insert into Room_facility (roomID, facilities) values (320, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (138, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (362, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (295, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (51, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (111, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (395, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (317, 'Sea View');
insert into Room_facility (roomID, facilities) values (208, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (375, 'Balcony');
insert into Room_facility (roomID, facilities) values (50, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (346, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (177, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (138, 'Sea View');
insert into Room_facility (roomID, facilities) values (54, 'Balcony');
insert into Room_facility (roomID, facilities) values (369, 'Sea View');
insert into Room_facility (roomID, facilities) values (94, 'Television');
insert into Room_facility (roomID, facilities) values (308, 'Sea View');
insert into Room_facility (roomID, facilities) values (280, 'Sea View');
insert into Room_facility (roomID, facilities) values (189, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (275, 'Balcony');
insert into Room_facility (roomID, facilities) values (245, 'Sea View');
insert into Room_facility (roomID, facilities) values (229, 'Television');
insert into Room_facility (roomID, facilities) values (191, 'Television');
insert into Room_facility (roomID, facilities) values (154, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (343, 'Balcony');
insert into Room_facility (roomID, facilities) values (86, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (175, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (337, 'Television');
insert into Room_facility (roomID, facilities) values (312, 'Sea View');
insert into Room_facility (roomID, facilities) values (28, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (5, 'Television');
insert into Room_facility (roomID, facilities) values (57, 'Balcony');
insert into Room_facility (roomID, facilities) values (197, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (233, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (247, 'Television');
insert into Room_facility (roomID, facilities) values (312, 'Balcony');
insert into Room_facility (roomID, facilities) values (119, 'Sea View');
insert into Room_facility (roomID, facilities) values (97, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (157, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (1, 'Sea View');
insert into Room_facility (roomID, facilities) values (101, 'Balcony');
insert into Room_facility (roomID, facilities) values (20, 'Television');
insert into Room_facility (roomID, facilities) values (400, 'Balcony');
insert into Room_facility (roomID, facilities) values (306, 'Sea View');
insert into Room_facility (roomID, facilities) values (101, 'Television');
insert into Room_facility (roomID, facilities) values (249, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (315, 'Balcony');
insert into Room_facility (roomID, facilities) values (59, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (259, 'Television');
insert into Room_facility (roomID, facilities) values (215, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (220, 'Balcony');
insert into Room_facility (roomID, facilities) values (192, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (168, 'Balcony');
insert into Room_facility (roomID, facilities) values (128, 'Television');
insert into Room_facility (roomID, facilities) values (327, 'Sea View');
insert into Room_facility (roomID, facilities) values (236, 'Sea View');
insert into Room_facility (roomID, facilities) values (350, 'Television');
insert into Room_facility (roomID, facilities) values (252, 'Sea View');
insert into Room_facility (roomID, facilities) values (187, 'Balcony');
insert into Room_facility (roomID, facilities) values (8, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (291, 'Television');
insert into Room_facility (roomID, facilities) values (171, 'Television');
insert into Room_facility (roomID, facilities) values (149, 'Sea View');
insert into Room_facility (roomID, facilities) values (101, 'Balcony');
insert into Room_facility (roomID, facilities) values (113, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (302, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (24, 'Balcony');
insert into Room_facility (roomID, facilities) values (312, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (296, 'Sea View');
insert into Room_facility (roomID, facilities) values (268, 'Sea View');
insert into Room_facility (roomID, facilities) values (23, 'Sea View');
insert into Room_facility (roomID, facilities) values (293, 'Balcony');
insert into Room_facility (roomID, facilities) values (21, 'Balcony');
insert into Room_facility (roomID, facilities) values (259, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (305, 'Television');
insert into Room_facility (roomID, facilities) values (196, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (258, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (386, 'Balcony');
insert into Room_facility (roomID, facilities) values (161, 'Balcony');
insert into Room_facility (roomID, facilities) values (389, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (13, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (352, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (65, 'Balcony');
insert into Room_facility (roomID, facilities) values (386, 'Sea View');
insert into Room_facility (roomID, facilities) values (108, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (12, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (44, 'Television');
insert into Room_facility (roomID, facilities) values (210, 'Television');
insert into Room_facility (roomID, facilities) values (369, 'Television');
insert into Room_facility (roomID, facilities) values (2, 'Sea View');
insert into Room_facility (roomID, facilities) values (234, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (28, 'Television');
insert into Room_facility (roomID, facilities) values (115, 'Balcony');
insert into Room_facility (roomID, facilities) values (369, 'Television');
insert into Room_facility (roomID, facilities) values (400, 'Refrigerator');
insert into Room_facility (roomID, facilities) values (352, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (37, 'Sea View');
insert into Room_facility (roomID, facilities) values (281, 'Free Wifi');
insert into Room_facility (roomID, facilities) values (270, 'Television');
insert into Room_facility (roomID, facilities) values (180, 'Sea View');
insert into Room_facility (roomID, facilities) values (64, 'Television');
